package lostfound.model;

import java.time.LocalDate;
import java.util.List;
import java.util.UUID;

public class Staff extends User implements Reportable {

    private String staffID;
    private String department;

    public Staff(String name, String email, String phone,
            String password, String department) {
        super(name, email, phone, password);
        this.staffID = "ST-" + UUID.randomUUID().toString().substring(0, 6).toUpperCase();
        this.department = department;
    }

    public String getStaffID() {
        return staffID;
    }

    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        if (department == null || department.trim().isEmpty()) {
            throw new IllegalArgumentException("Department cannot be empty.");
        }
        this.department = department.trim();
    }

    public boolean verifyItem(Item item) {
        if (Item.STATUS_SUBMITTED.equals(item.getStatus())) {
            item.setStatus(Item.STATUS_VERIFIED);
            return true;
        }
        return false;
    }

    public boolean approveClaim(ClaimRequest claim, ItemFound foundItem) {
        if (ClaimRequest.STATUS_PENDING.equals(claim.getClaimStatus())) {
            claim.setClaimStatus(ClaimRequest.STATUS_APPROVED);
            foundItem.setStatus(Item.STATUS_CLAIMED);
            return true;
        }
        return false;
    }

    public boolean rejectClaim(ClaimRequest claim, String reason) {
        if (ClaimRequest.STATUS_PENDING.equals(claim.getClaimStatus())) {
            claim.setClaimStatus(ClaimRequest.STATUS_REJECTED);
            claim.setRejectionReason(reason);
            return true;
        }
        return false;
    }

    @Override
    public void generateReport(List<Item> items, List<ClaimRequest> claims) {
        int found = 0;
        int lost = 0;
        int pendingClaims = 0;

        for (Item item : items) {
            if (item instanceof ItemFound) {
                found++;
            } else if (item instanceof ItemLost) {
                lost++;
            }
        }

        for (ClaimRequest claim : claims) {
            if (ClaimRequest.STATUS_PENDING.equals(claim.getClaimStatus())) {
                pendingClaims++;
            }
        }

        System.out.println("========== SYSTEM REPORT ==========");
        System.out.println("Generated by: " + getName());
        System.out.println("Date: " + LocalDate.now());
        System.out.println("Found Items: " + found);
        System.out.println("Lost Reports: " + lost);
        System.out.println("Total Claims: " + claims.size());
        System.out.println("Pending Claims: " + pendingClaims);
        System.out.println("===================================");
    }

    @Override
    public String getRole() {
        return "Admin";
    }

    @Override
    public String getSummary() {
        return staffID + " | " + getName()
                + " | " + department
                + " | " + getEmail();
    }
}
