/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package lostfound.da;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import lostfound.db.DBConnection;
import lostfound.model.Item;
import lostfound.model.ItemFound;
import lostfound.model.ItemLost;
/**
 *
 * @author danis
 */
public class ItemDA {
    
    public boolean insertLostItem(ItemLost lostItem){
        String sql = "INSERT INTO items (item_id, item_type, item_name, description, category, color, status, "
                     + "submitted_date, location_lost, date_lost, reporter_id)"
                     + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        
        try (Connection conn = DBConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)){
            
            // 1. Core Automated Base Fields (Extracted straight from your Java object logic)
            pstmt.setString(1, lostItem.getItemID());              // Auto-generated by UUID
            pstmt.setString(2, "LOST");                            // Discriminator for Single Table Inheritance
            pstmt.setString(3, lostItem.getItemName());            // User UI Input
            pstmt.setString(4, lostItem.getDescription());         // User UI Input
            pstmt.setString(5, lostItem.getCategory().name());     // Selected Enum converted to String
            pstmt.setString(6, lostItem.getColor());                // User UI Input
            
            // 2. Automated Status & Submission Tracking Fields
            pstmt.setString(7, lostItem.getStatus());              // Auto-set to "PENDING"
            pstmt.setDate(8, java.sql.Date.valueOf(lostItem.getSubmittedDate())); // Auto-set via LocalDate.now()
            
            // 3. Subclass Specific Fields
            pstmt.setString(9, lostItem.getLocationLost());        // User UI Input
            pstmt.setDate(10, java.sql.Date.valueOf(lostItem.getDateLost())); // User UI Input (e.g., from Form)
            pstmt.setString(11, lostItem.getReporterID());          // Programmatically filled from active Session ID
            
            // Execute the insertion query
            int rowsAffected = pstmt.executeUpdate();
            return rowsAffected > 0;
        } catch (Exception e){
            e.printStackTrace();
            return false;
        }
    }
    
    public boolean insertFoundItem(ItemFound foundItem){
        String sql = "INSERT INTO items (item_id, item_type, item_name, description, category, color, status, "
                     + "submitted_date, location_found, date_found, store_at, reporter_id)"
                     + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        
        try(Connection conn = DBConnection.getConnection();
            PreparedStatement pstmt = conn.prepareStatement(sql)){
                
            pstmt.setString(1, foundItem.getItemID());
            pstmt.setString(2, "FOUND");                           // Discriminator value
            pstmt.setString(3, foundItem.getItemName());            // User UI Input
            pstmt.setString(4, foundItem.getDescription());         // User UI Input
            pstmt.setString(5, foundItem.getCategory().name());     // Enum to String
            pstmt.setString(6, foundItem.getColor());               // User UI Input
            
            // 2. Automated Status & Submission Tracking Fields
            pstmt.setString(7, foundItem.getStatus());              // Auto-sets to STATUS_SUBMITTED
            pstmt.setDate(8, java.sql.Date.valueOf(foundItem.getSubmittedDate())); // Current Date
            
            // 3. Subclass Specific Fields (Found)
            pstmt.setString(9, foundItem.getLocationFound());       // User UI Input
            pstmt.setDate(10, java.sql.Date.valueOf(foundItem.getDateFound())); // User UI Input
            pstmt.setString(11, foundItem.getStoreAt());            // User UI Input
            pstmt.setString(12, foundItem.getSubmitterID());        // Session System Input
            
            int rowsAffected = pstmt.executeUpdate();
            return rowsAffected > 0;
            
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }
}
