/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lostfound.gui;

import lostfound.da.ItemDA;
import lostfound.session.SessionManager;

/**
 *
 * @author danis
 */
public class Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());
    private javax.swing.JButton refreshActivityBtn;

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        addActivityRefreshButton();
        loadActivityFeed();
    }

    private void loadActivityFeed() {
        ItemDA itemDA = new ItemDA();
        activityfeedTable.setModel(itemDA.getAllItemsTableModel());
    }

    private void addActivityRefreshButton() {
        refreshActivityBtn = new javax.swing.JButton("Refresh");
        refreshActivityBtn.setBackground(new java.awt.Color(244, 85, 0));
        refreshActivityBtn.setFont(new java.awt.Font("Arial", 0, 14));
        refreshActivityBtn.setForeground(new java.awt.Color(235, 233, 228));
        refreshActivityBtn.addActionListener(evt -> loadActivityFeed());
        jPanel1.add(refreshActivityBtn);
        refreshActivityBtn.setBounds(650, 220, 110, 30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        homeBtn = new javax.swing.JButton();
        browseBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        userserviceBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        quickactionLabel = new javax.swing.JLabel();
        reportlostitemBtn = new javax.swing.JButton();
        reportfounditemBtn = new javax.swing.JButton();
        browsecatalogBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        activityfeedTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(235, 233, 228));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 550));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(244, 85, 0));
        jPanel2.setForeground(new java.awt.Color(244, 85, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 550));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Nirmala Text", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(235, 233, 228));
        jLabel4.setText("Lost&FoundU");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 50, 170, 56);

        homeBtn.setBackground(new java.awt.Color(235, 233, 228));
        homeBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        homeBtn.setText("Home");
        homeBtn.addActionListener(this::homeBtnActionPerformed);
        jPanel2.add(homeBtn);
        homeBtn.setBounds(10, 170, 180, 30);

        browseBtn.setBackground(new java.awt.Color(235, 233, 228));
        browseBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        browseBtn.setText("Browse");
        browseBtn.addActionListener(this::browseBtnActionPerformed);
        jPanel2.add(browseBtn);
        browseBtn.setBounds(10, 220, 180, 30);

        searchBtn.setBackground(new java.awt.Color(235, 233, 228));
        searchBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        searchBtn.setText("Search");
        searchBtn.setToolTipText("");
        searchBtn.addActionListener(this::searchBtnActionPerformed);
        jPanel2.add(searchBtn);
        searchBtn.setBounds(10, 270, 180, 30);

        userserviceBtn.setBackground(new java.awt.Color(235, 233, 228));
        userserviceBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        userserviceBtn.setText("User Service");
        userserviceBtn.setToolTipText("");
        userserviceBtn.addActionListener(this::userserviceBtnActionPerformed);
        jPanel2.add(userserviceBtn);
        userserviceBtn.setBounds(10, 320, 180, 30);

        logoutBtn.setBackground(new java.awt.Color(235, 233, 228));
        logoutBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(this::logoutBtnActionPerformed);
        jPanel2.add(logoutBtn);
        logoutBtn.setBounds(10, 500, 180, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 200, 550);

        quickactionLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        quickactionLabel.setText("Quick Action:");
        jPanel1.add(quickactionLabel);
        quickactionLabel.setBounds(240, 100, 130, 22);

        reportlostitemBtn.setBackground(new java.awt.Color(244, 85, 0));
        reportlostitemBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        reportlostitemBtn.setForeground(new java.awt.Color(235, 233, 228));
        reportlostitemBtn.setText("Report Lost Item");
        reportlostitemBtn.addActionListener(this::reportlostitemBtnActionPerformed);
        jPanel1.add(reportlostitemBtn);
        reportlostitemBtn.setBounds(240, 140, 150, 50);

        reportfounditemBtn.setBackground(new java.awt.Color(244, 85, 0));
        reportfounditemBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        reportfounditemBtn.setForeground(new java.awt.Color(235, 233, 228));
        reportfounditemBtn.setText("Report Found Item");
        reportfounditemBtn.addActionListener(this::reportfounditemBtnActionPerformed);
        jPanel1.add(reportfounditemBtn);
        reportfounditemBtn.setBounds(420, 140, 150, 50);

        browsecatalogBtn.setBackground(new java.awt.Color(244, 85, 0));
        browsecatalogBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        browsecatalogBtn.setForeground(new java.awt.Color(235, 233, 228));
        browsecatalogBtn.setText("Browse Catalog");
        browsecatalogBtn.addActionListener(this::browsecatalogBtnActionPerformed);
        jPanel1.add(browsecatalogBtn);
        browsecatalogBtn.setBounds(600, 140, 150, 50);

        activityfeedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(activityfeedTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(240, 260, 520, 210);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Activity Feed:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(240, 220, 130, 22);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lostfound/gambar/logo.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(350, 0, 300, 100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
        Dashboard home = new Dashboard();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void browseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBtnActionPerformed
        // TODO add your handling code here:
        BrowseItems browse = new BrowseItems();
        browse.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_browseBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        SearchItems search = new SearchItems();
        search.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_searchBtnActionPerformed

    private void userserviceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userserviceBtnActionPerformed
        // TODO add your handling code here:
        UserService userService = new UserService();
        userService.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_userserviceBtnActionPerformed

    private void reportlostitemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportlostitemBtnActionPerformed
        // TODO add your handling code here:
        ReportLostItem lostItem = new ReportLostItem();
        lostItem.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_reportlostitemBtnActionPerformed

    private void reportfounditemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportfounditemBtnActionPerformed
        // TODO add your handling code here:
        ReportFoundItem foundItem = new ReportFoundItem();
        foundItem.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_reportfounditemBtnActionPerformed

    private void browsecatalogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browsecatalogBtnActionPerformed
        // TODO add your handling code here:
        BrowseItems browse = new BrowseItems();
        browse.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_browsecatalogBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        SessionManager.getInstance().logout();
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable activityfeedTable;
    private javax.swing.JButton browseBtn;
    private javax.swing.JButton browsecatalogBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JLabel quickactionLabel;
    private javax.swing.JButton reportfounditemBtn;
    private javax.swing.JButton reportlostitemBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton userserviceBtn;
    // End of variables declaration//GEN-END:variables
}
