/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lostfound.gui;

import javax.swing.JOptionPane;

import javax.swing.JOptionPane;
import lostfound.db.DBConnection;
import lostfound.da.UserDA;
/**
 *
 * @author danis
 */
public class ForgotPassword extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ForgotPassword.class.getName());
    private DBConnection connection;
    private UserDA userDA;
    /**
     * Creates new form ForgotPassword
     */
    public ForgotPassword() {
        initComponents();
        
        connection = new DBConnection();
        userDA = new UserDA();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        newpassTextField = new javax.swing.JPasswordField();
        confirmpassTextField = new javax.swing.JPasswordField();
        newpassLabel = new javax.swing.JLabel();
        confirmpassLabel = new javax.swing.JLabel();
        changepassBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(235, 233, 228));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 550));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(244, 85, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(270, 550));
        jPanel2.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(235, 233, 228));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(235, 233, 228));
        jLabel1.setText("Forgot Password");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(40, 260, 200, 28);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 270, 550);

        emailLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        emailLabel.setText("Email:");
        jPanel1.add(emailLabel);
        emailLabel.setBounds(330, 170, 50, 17);

        emailTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(emailTextField);
        emailTextField.setBounds(330, 200, 410, 23);

        newpassTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(newpassTextField);
        newpassTextField.setBounds(330, 270, 410, 23);

        confirmpassTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(confirmpassTextField);
        confirmpassTextField.setBounds(330, 340, 410, 22);

        newpassLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        newpassLabel.setText("New Password:");
        jPanel1.add(newpassLabel);
        newpassLabel.setBounds(330, 240, 130, 17);

        confirmpassLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        confirmpassLabel.setText("Confirm Password:");
        jPanel1.add(confirmpassLabel);
        confirmpassLabel.setBounds(330, 310, 140, 17);

        changepassBtn.setBackground(new java.awt.Color(244, 85, 0));
        changepassBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        changepassBtn.setForeground(new java.awt.Color(235, 233, 228));
        changepassBtn.setText("Change password");
        changepassBtn.addActionListener(this::changepassBtnActionPerformed);
        jPanel1.add(changepassBtn);
        changepassBtn.setBounds(330, 390, 410, 30);

        jLabel2.setText("<html><font color=\"blue\"><u>Back to login</u></font></html>");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(500, 430, 80, 16);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lostfound/gambar/logo.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(360, 20, 360, 140);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changepassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changepassBtnActionPerformed
        String email = emailTextField.getText().trim();
        String password = new String(newpassTextField.getPassword()).trim();
        String confirmpass = new String(confirmpassTextField.getPassword()).trim();
        
        //validate empty inputs
        if(email.isEmpty() || password.isEmpty() || confirmpass.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please fill in all fields!", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        //validate new password and confirm password is match
        if(!confirmpass.equals(password)){
            JOptionPane.showMessageDialog(this, "Password do not match! Please check your entries.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        //validate new password length
        if (confirmpass.length() < 8) {
            JOptionPane.showMessageDialog(this, "Password must be at least 8 characters long!", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        //validate if email is exist in the database
        if (!userDA.emailExists(email)) {
            JOptionPane.showMessageDialog(this, "The email address entered does not exist in our system.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        //update password query
        boolean updateSuccess = userDA.forgotPassword(email, confirmpass);
        
        if(updateSuccess){
            JOptionPane.showMessageDialog(this, "Password updated successfully!\nYou will now redirected to the Login page.", "Success", JOptionPane.INFORMATION_MESSAGE);
            
            Login login = new Login();
            login.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to update password. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_changepassBtnActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ForgotPassword().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changepassBtn;
    private javax.swing.JLabel confirmpassLabel;
    private javax.swing.JPasswordField confirmpassTextField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel newpassLabel;
    private javax.swing.JPasswordField newpassTextField;
    // End of variables declaration//GEN-END:variables
}
