/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lostfound.gui;

import javax.swing.JOptionPane;
import lostfound.db.DBConnection;
import lostfound.da.UserDA;
import lostfound.session.SessionManager;
/**
 *
 * @author izzati
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());
    private DBConnection connection;
    private UserDA userDA;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        connection = new DBConnection();
        userDA = new UserDA();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JPasswordField();
        passwordLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(235, 233, 228));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(null);

        nameLabel.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        nameLabel.setText("Email:");
        jPanel1.add(nameLabel);
        nameLabel.setBounds(1010, 420, 60, 21);

        emailTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        emailTextField.addActionListener(this::emailTextFieldActionPerformed);
        jPanel1.add(emailTextField);
        emailTextField.setBounds(1010, 450, 410, 23);

        passwordTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(passwordTextField);
        passwordTextField.setBounds(1010, 520, 410, 23);

        passwordLabel.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        passwordLabel.setText("Password:");
        jPanel1.add(passwordLabel);
        passwordLabel.setBounds(1010, 490, 90, 21);

        jLabel2.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        jLabel2.setText("<html><font color=\"blue\"><u>Forgot Password?</u></font></html>");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(1010, 570, 110, 16);

        jLabel4.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        jLabel4.setText("<html><font color=\"blue\"><u>Staff Login</u></font></html>");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(1350, 570, 70, 16);

        loginBtn.setBackground(new java.awt.Color(244, 85, 0));
        loginBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(235, 233, 228));
        loginBtn.setText("LOGIN");
        loginBtn.addActionListener(this::loginBtnActionPerformed);
        jPanel1.add(loginBtn);
        loginBtn.setBounds(1010, 610, 410, 30);

        jLabel5.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        jLabel5.setText("<html>Don't have an account? <font color=\"blue\"><u>Register</u></font></html>");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(1010, 660, 190, 16);

        jLabel7.setFont(new java.awt.Font("STHupo", 1, 60)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(231, 85, 49));
        jLabel7.setText("lost&foundU");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(190, 470, 360, 62);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Bell MT", 1, 48)); // NOI18N
        jLabel6.setText("Login");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(1010, 330, 159, 54);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lostfound/gambar/logostampp.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(1560, 100, 250, 250);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lostfound/gambar/bluewhitebg.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(730, 0, 1190, 1080);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lostfound/gambar/bgpic.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 730, 1080);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        String email = emailTextField.getText().trim();
        String password = new String(passwordTextField.getPassword()).trim();

        //input field validation
        if(email.isEmpty() || password.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please fill in all the fields!", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        //query
        int loginResult = userDA.loginUser(email, password);

        switch (loginResult){
            case 1:
            String[] sessionUser = userDA.getUserSessionByEmail(email);
            if (sessionUser == null) {
                JOptionPane.showMessageDialog(this, "Login successful, but user session could not be loaded.", "System Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            SessionManager.getInstance().loginDatabaseUser(sessionUser[0], sessionUser[1], sessionUser[2]);
            JOptionPane.showMessageDialog(this, "Login Succesful!\nWelcome Back, " + sessionUser[1] + ".", "Success", JOptionPane.INFORMATION_MESSAGE);

            Dashboard dashboard = new Dashboard();
            dashboard.setVisible(true);
            this.dispose();
            break;

            case 0:
            JOptionPane.showMessageDialog(this, "The email address entered does not exist in our database.", "Login Failed", JOptionPane.ERROR_MESSAGE);
            break;

            case -1:
            JOptionPane.showMessageDialog(this, "Incorrect password! Please try again.", "Login Failed", JOptionPane.ERROR_MESSAGE);
            passwordTextField.setText("");
            passwordTextField.requestFocus();
            break;

            default:
            JOptionPane.showMessageDialog(this, "An unexpected error occured while while connecting to the database.", "System Error", JOptionPane.ERROR_MESSAGE);
            break;
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        ForgotPassword pass = new ForgotPassword();
        pass.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        StaffLogin staffLogin = new StaffLogin();
        staffLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        Register register = new Register();
        register.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordTextField;
    // End of variables declaration//GEN-END:variables
}
