/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lostfound.gui;

import javax.swing.JOptionPane;
import lostfound.db.DBConnection;
import lostfound.da.UserDA;
/**
 *
 * @author danis
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());
    private DBConnection connection;
    private UserDA userDA;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        connection = new DBConnection();
        userDA = new UserDA();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JPasswordField();
        passwordLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(235, 233, 228));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 550));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(244, 85, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(270, 550));
        jPanel2.setLayout(null);

        loginLabel.setBackground(new java.awt.Color(235, 233, 228));
        loginLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(235, 233, 228));
        loginLabel.setText("Login");
        jPanel2.add(loginLabel);
        loginLabel.setBounds(100, 260, 70, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 270, 550);

        nameLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nameLabel.setText("Email:");
        jPanel1.add(nameLabel);
        nameLabel.setBounds(330, 160, 60, 17);

        emailTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        emailTextField.addActionListener(this::emailTextFieldActionPerformed);
        jPanel1.add(emailTextField);
        emailTextField.setBounds(330, 190, 410, 23);

        passwordTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(passwordTextField);
        passwordTextField.setBounds(330, 270, 410, 23);

        passwordLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        passwordLabel.setText("Password:");
        jPanel1.add(passwordLabel);
        passwordLabel.setBounds(330, 240, 80, 17);

        jLabel2.setText("<html><font color=\"blue\"><u>Forgot Password?</u></font></html>");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(330, 320, 110, 16);

        jLabel4.setText("<html><font color=\"blue\"><u>Staff Login</u></font></html>");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(680, 320, 70, 16);

        loginBtn.setBackground(new java.awt.Color(244, 85, 0));
        loginBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(235, 233, 228));
        loginBtn.setText("Login");
        loginBtn.addActionListener(this::loginBtnActionPerformed);
        jPanel1.add(loginBtn);
        loginBtn.setBounds(330, 360, 410, 30);

        jLabel5.setText("<html>Don't have an account? <font color=\"blue\"><u>Register</u></font></html>");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(450, 400, 190, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        String email = emailTextField.getText().trim();
        String password = new String(passwordTextField.getPassword()).trim();

        //input field validation
        if(email.isEmpty() || password.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please fill in all the fields!", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        //query
        int loginResult = userDA.loginUser(email, password);

        switch (loginResult){
            case 1:
            JOptionPane.showMessageDialog(this, "Login Succesful!\nWelcome Back.", "Success", JOptionPane.INFORMATION_MESSAGE);

            Dashboard dashboard = new Dashboard();
            dashboard.setVisible(true);
            this.dispose();
            break;

            case 0:
            JOptionPane.showMessageDialog(this, "The email address entered does not exist in our database.", "Login Failed", JOptionPane.ERROR_MESSAGE);
            break;

            case -1:
            JOptionPane.showMessageDialog(this, "Incorrect password! Please try again.", "Login Failed", JOptionPane.ERROR_MESSAGE);
            passwordTextField.setText("");
            passwordTextField.requestFocus();
            break;

            default:
            JOptionPane.showMessageDialog(this, "An unexpected error occured while while connecting to the database.", "System Error", JOptionPane.ERROR_MESSAGE);
            break;
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        ForgotPassword pass = new ForgotPassword();
        pass.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        StaffLogin staffLogin = new StaffLogin();
        staffLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        Register register = new Register();
        register.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordTextField;
    // End of variables declaration//GEN-END:variables
}
