/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lostfound.gui;

import javax.swing.JOptionPane;
import lostfound.da.ClaimDA;
import lostfound.da.ItemDA;
import lostfound.session.SessionManager;

/**
 *
 * @author danis
 */
public class ManageReports extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManageReports.class.getName());

    /**
     * Creates new form ManageReports
     */
    public ManageReports() {
        initComponents();
        loadReports();
    }
    
    private String getUserIDOrRedirect() {
        String userID = SessionManager.getInstance().getAccountID();
        if (userID == null) {
            JOptionPane.showMessageDialog(this, "Please log in to manage reports.", "Session Error", JOptionPane.ERROR_MESSAGE);
            Login login = new Login();
            login.setVisible(true);
            this.dispose();
        }
        return userID;
    }
    
    private boolean isClaimMode() {
        return reportTypeComboBox.getSelectedIndex() == 1;
    }
    
    private void loadReports() {
        String userID = getUserIDOrRedirect();
        if (userID == null) {
            return;
        }
        
        if (isClaimMode()) {
            ClaimDA claimDA = new ClaimDA();
            reportsTable.setModel(claimDA.getClaimsByUserTableModel(userID));
        } else {
            ItemDA itemDA = new ItemDA();
            reportsTable.setModel(itemDA.getUserItemsManagementTableModel(userID));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        homeBtn = new javax.swing.JButton();
        browseBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        userserviceBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        reportTypeComboBox = new javax.swing.JComboBox<>();
        refreshBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        reportsTable = new javax.swing.JTable();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(235, 233, 228));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 550));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(244, 85, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 550));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Nirmala Text", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(235, 233, 228));
        jLabel4.setText("Lost&FoundU");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 50, 170, 56);

        homeBtn.setBackground(new java.awt.Color(235, 233, 228));
        homeBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        homeBtn.setText("Home");
        homeBtn.addActionListener(this::homeBtnActionPerformed);
        jPanel2.add(homeBtn);
        homeBtn.setBounds(10, 170, 180, 30);

        browseBtn.setBackground(new java.awt.Color(235, 233, 228));
        browseBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        browseBtn.setText("Browse");
        browseBtn.addActionListener(this::browseBtnActionPerformed);
        jPanel2.add(browseBtn);
        browseBtn.setBounds(10, 220, 180, 30);

        searchBtn.setBackground(new java.awt.Color(235, 233, 228));
        searchBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        searchBtn.setText("Search");
        searchBtn.setToolTipText("");
        searchBtn.addActionListener(this::searchBtnActionPerformed);
        jPanel2.add(searchBtn);
        searchBtn.setBounds(10, 270, 180, 30);

        userserviceBtn.setBackground(new java.awt.Color(235, 233, 228));
        userserviceBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        userserviceBtn.setText("User Service");
        userserviceBtn.setToolTipText("");
        userserviceBtn.addActionListener(this::userserviceBtnActionPerformed);
        jPanel2.add(userserviceBtn);
        userserviceBtn.setBounds(10, 320, 180, 30);

        logoutBtn.setBackground(new java.awt.Color(235, 233, 228));
        logoutBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(this::logoutBtnActionPerformed);
        jPanel2.add(logoutBtn);
        logoutBtn.setBounds(10, 500, 180, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 200, 550);

        titleLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        titleLabel.setText("Manage Report");
        jPanel1.add(titleLabel);
        titleLabel.setBounds(230, 50, 170, 22);

        reportTypeComboBox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        reportTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item Reports", "Claim Requests" }));
        reportTypeComboBox.addActionListener(this::reportTypeComboBoxActionPerformed);
        jPanel1.add(reportTypeComboBox);
        reportTypeComboBox.setBounds(430, 50, 150, 25);

        refreshBtn.setBackground(new java.awt.Color(244, 85, 0));
        refreshBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        refreshBtn.setForeground(new java.awt.Color(235, 233, 228));
        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(this::refreshBtnActionPerformed);
        jPanel1.add(refreshBtn);
        refreshBtn.setBounds(650, 50, 110, 30);

        reportsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(reportsTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(230, 100, 530, 340);

        editBtn.setBackground(new java.awt.Color(244, 85, 0));
        editBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        editBtn.setForeground(new java.awt.Color(235, 233, 228));
        editBtn.setText("Edit");
        editBtn.addActionListener(this::editBtnActionPerformed);
        jPanel1.add(editBtn);
        editBtn.setBounds(500, 460, 120, 30);

        deleteBtn.setBackground(new java.awt.Color(244, 85, 0));
        deleteBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(235, 233, 228));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(this::deleteBtnActionPerformed);
        jPanel1.add(deleteBtn);
        deleteBtn.setBounds(640, 460, 120, 30);

        backBtn.setBackground(new java.awt.Color(244, 85, 0));
        backBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(235, 233, 228));
        backBtn.setText("Back");
        backBtn.addActionListener(this::backBtnActionPerformed);
        jPanel1.add(backBtn);
        backBtn.setBounds(230, 460, 120, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        Dashboard home = new Dashboard();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void browseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBtnActionPerformed
        BrowseItems browse = new BrowseItems();
        browse.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_browseBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        SearchItems search = new SearchItems();
        search.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_searchBtnActionPerformed

    private void userserviceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userserviceBtnActionPerformed
        UserService userService = new UserService();
        userService.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_userserviceBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        SessionManager.getInstance().logout();
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void reportTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportTypeComboBoxActionPerformed
        loadReports();
    }//GEN-LAST:event_reportTypeComboBoxActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        loadReports();
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        int selectedRow = reportsTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a report to edit.", "Selection Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (isClaimMode()) {
            editClaim(selectedRow);
        } else {
            editItemReport(selectedRow);
        }
    }//GEN-LAST:event_editBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int selectedRow = reportsTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a report to delete.", "Selection Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String userID = getUserIDOrRedirect();
        if (userID == null) {
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this, "Delete selected report?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        
        boolean success;
        if (isClaimMode()) {
            String claimID = reportsTable.getValueAt(selectedRow, 0).toString();
            success = new ClaimDA().deleteUserClaim(claimID, userID);
        } else {
            String itemID = reportsTable.getValueAt(selectedRow, 0).toString();
            success = new ItemDA().deleteUserItemReport(itemID, userID);
        }
        
        if (success) {
            JOptionPane.showMessageDialog(this, "Report deleted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
            loadReports();
        } else {
            JOptionPane.showMessageDialog(this, "Delete failed. Claims can only be deleted while PENDING.", "Delete Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        UserService userService = new UserService();
        userService.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void editItemReport(int selectedRow) {
        String userID = getUserIDOrRedirect();
        if (userID == null) {
            return;
        }
        
        String itemID = reportsTable.getValueAt(selectedRow, 0).toString();
        String currentName = valueAt(selectedRow, 2);
        String currentDescription = valueAt(selectedRow, 3);
        String currentColor = valueAt(selectedRow, 5);
        String currentLocation = valueAt(selectedRow, 6);
        
        String itemName = JOptionPane.showInputDialog(this, "Item name:", currentName);
        if (itemName == null) return;
        String description = JOptionPane.showInputDialog(this, "Description:", currentDescription);
        if (description == null) return;
        String color = JOptionPane.showInputDialog(this, "Color:", currentColor);
        if (color == null) return;
        String location = JOptionPane.showInputDialog(this, "Location:", currentLocation);
        if (location == null) return;
        
        if (itemName.trim().isEmpty() || location.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Item name and location cannot be empty.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        boolean success = new ItemDA().updateUserItemReport(
                itemID, userID, itemName.trim(), description.trim(), color.trim(), location.trim());
        
        if (success) {
            JOptionPane.showMessageDialog(this, "Item report updated successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
            loadReports();
        } else {
            JOptionPane.showMessageDialog(this, "Update failed.", "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void editClaim(int selectedRow) {
        String userID = getUserIDOrRedirect();
        if (userID == null) {
            return;
        }
        
        String claimID = reportsTable.getValueAt(selectedRow, 0).toString();
        String currentProof = valueAt(selectedRow, 2);
        String proof = JOptionPane.showInputDialog(this, "Proof of ownership:", currentProof);
        if (proof == null) {
            return;
        }
        
        if (proof.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Proof cannot be empty.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        boolean success = new ClaimDA().updateUserClaimProof(claimID, userID, proof.trim());
        
        if (success) {
            JOptionPane.showMessageDialog(this, "Claim proof updated successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
            loadReports();
        } else {
            JOptionPane.showMessageDialog(this, "Update failed. Claims can only be edited while PENDING.", "Update Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private String valueAt(int row, int column) {
        Object value = reportsTable.getValueAt(row, column);
        return value == null ? "" : value.toString();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(() -> new ManageReports().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton browseBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JComboBox<String> reportTypeComboBox;
    private javax.swing.JTable reportsTable;
    private javax.swing.JButton searchBtn;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton userserviceBtn;
    // End of variables declaration//GEN-END:variables
}
