/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lostfound.gui;

import javax.swing.JOptionPane;
import lostfound.db.DBConnection;
import lostfound.da.UserDA;

/**
 *
 * @author danis
 */
public class Register extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Register.class.getName());
    private DBConnection connection;
    private UserDA userDA;
    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        connection = new DBConnection();
        userDA = new UserDA();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        registerLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        phonenumberLabel = new javax.swing.JLabel();
        phoneTextField = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        loginClickHere = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(235, 233, 228));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(244, 85, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(270, 550));
        jPanel2.setLayout(null);

        registerLabel.setBackground(new java.awt.Color(235, 233, 228));
        registerLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        registerLabel.setForeground(new java.awt.Color(235, 233, 228));
        registerLabel.setText("Register");
        jPanel2.add(registerLabel);
        registerLabel.setBounds(80, 260, 100, 28);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 270, 550);

        passwordLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        passwordLabel.setText("Password:");
        jPanel1.add(passwordLabel);
        passwordLabel.setBounds(330, 320, 130, 17);

        nameLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nameLabel.setText("Name:");
        jPanel1.add(nameLabel);
        nameLabel.setBounds(330, 110, 50, 17);

        nameTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(nameTextField);
        nameTextField.setBounds(330, 140, 420, 22);

        emailLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        emailLabel.setText("Email:");
        jPanel1.add(emailLabel);
        emailLabel.setBounds(330, 180, 50, 17);

        emailTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(emailTextField);
        emailTextField.setBounds(330, 210, 420, 23);

        phonenumberLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        phonenumberLabel.setText("Phone Number:");
        jPanel1.add(phonenumberLabel);
        phonenumberLabel.setBounds(330, 250, 130, 17);

        phoneTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(phoneTextField);
        phoneTextField.setBounds(330, 280, 420, 23);

        submitBtn.setBackground(new java.awt.Color(244, 85, 0));
        submitBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        submitBtn.setForeground(new java.awt.Color(235, 233, 228));
        submitBtn.setText("Submit");
        submitBtn.addActionListener(this::submitBtnActionPerformed);
        jPanel1.add(submitBtn);
        submitBtn.setBounds(330, 430, 420, 30);

        loginClickHere.setText("<html>Already have an account? <font color=\"blue\"><u>Click here</u></font></html>");
        loginClickHere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginClickHereMouseClicked(evt);
            }
        });
        jPanel1.add(loginClickHere);
        loginClickHere.setBounds(330, 390, 210, 16);

        passwordTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        passwordTextField.addActionListener(this::passwordTextFieldActionPerformed);
        jPanel1.add(passwordTextField);
        passwordTextField.setBounds(330, 350, 420, 23);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lostfound/gambar/logo.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(360, 0, 360, 110);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        String name = nameTextField.getText().trim(); 
        String email = emailTextField.getText().trim();
        String phone = phoneTextField.getText().trim();
        String password = new String(passwordTextField.getPassword()).trim();
        
        //validation checks
        if(name.isEmpty() || email.isEmpty() || phone.isEmpty() || password.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please fill in all fields!", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        //validate email format
        if(!email.contains("@") || !email.contains(".")){
            JOptionPane.showMessageDialog(this, "Please enter a valid email address!", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        //validate phone number
        if(phone.replaceAll("[^0-9]", "").length() < 10){
            JOptionPane.showMessageDialog(this, "Please enter a valid phone number (at least 10 digits)", "Validataion Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        //validate password length
        if(password.length() < 8){
            JOptionPane.showMessageDialog(this, "Password must be at least 8 characters long!", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Check if email already exists
        if(userDA.emailExists(email)){
            JOptionPane.showMessageDialog(this, "Email already registered! Please use a different email to register.", "Registration Failed", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        boolean success = userDA.registerUser(name, email, phone, password);
        
        if (success){
            JOptionPane.showMessageDialog(this, "Registration Successful!\nWelcome, " + name + "!", "Success", JOptionPane.INFORMATION_MESSAGE);
            
            
            nameTextField.setText("");
            emailTextField.setText("");
            phoneTextField.setText("");
            passwordTextField.setText("");
            
            Login login = new Login();
            login.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Registration failed, please try again.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_submitBtnActionPerformed

    private void loginClickHereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginClickHereMouseClicked
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_loginClickHereMouseClicked

    private void passwordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Register().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel loginClickHere;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JLabel phonenumberLabel;
    private javax.swing.JLabel registerLabel;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
