/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lostfound.gui;

import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;
import lostfound.model.Category;
import lostfound.model.Item;
import lostfound.model.ItemLost;
import lostfound.da.ItemDA;
import lostfound.model.ItemFactory;

/**
 *
 * @author danis
 */
public class ReportLostItem extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReportLostItem.class.getName());
    
    /**
     * Creates new form ReportLostItem
     */
    public ReportLostItem() {
        initComponents();
        
        categoryDropDown.removeAllItems();
        
        for(Category cat : Category.values()){
            categoryDropDown.addItem(cat.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        homeBtn = new javax.swing.JButton();
        browseBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        userserviceBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        itemnameLabel = new javax.swing.JLabel();
        itemnameTextField = new javax.swing.JTextField();
        descriptionLabel = new javax.swing.JLabel();
        descriptionTextField = new javax.swing.JTextField();
        categoryLabel = new javax.swing.JLabel();
        categoryDropDown = new javax.swing.JComboBox<>();
        colorLabel = new javax.swing.JLabel();
        colorTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lastseenTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        datelostTextField = new javax.swing.JFormattedTextField();
        submitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(235, 233, 228));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 550));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(244, 85, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 550));
        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Nirmala Text", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(235, 233, 228));
        jLabel5.setText("Lost&FoundU");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 50, 170, 56);

        homeBtn.setBackground(new java.awt.Color(235, 233, 228));
        homeBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        homeBtn.setText("Home");
        homeBtn.addActionListener(this::homeBtnActionPerformed);
        jPanel2.add(homeBtn);
        homeBtn.setBounds(10, 170, 180, 30);

        browseBtn.setBackground(new java.awt.Color(235, 233, 228));
        browseBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        browseBtn.setText("Browse");
        browseBtn.addActionListener(this::browseBtnActionPerformed);
        jPanel2.add(browseBtn);
        browseBtn.setBounds(10, 220, 180, 30);

        searchBtn.setBackground(new java.awt.Color(235, 233, 228));
        searchBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        searchBtn.setText("Search");
        searchBtn.setToolTipText("");
        searchBtn.addActionListener(this::searchBtnActionPerformed);
        jPanel2.add(searchBtn);
        searchBtn.setBounds(10, 270, 180, 30);

        userserviceBtn.setBackground(new java.awt.Color(235, 233, 228));
        userserviceBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        userserviceBtn.setText("User Service");
        userserviceBtn.setToolTipText("");
        userserviceBtn.addActionListener(this::userserviceBtnActionPerformed);
        jPanel2.add(userserviceBtn);
        userserviceBtn.setBounds(10, 320, 180, 30);

        logoutBtn.setBackground(new java.awt.Color(235, 233, 228));
        logoutBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(this::logoutBtnActionPerformed);
        jPanel2.add(logoutBtn);
        logoutBtn.setBounds(10, 500, 180, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 200, 550);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("File a New Lost Item Report");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(230, 50, 250, 22);

        backBtn.setBackground(new java.awt.Color(244, 85, 0));
        backBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(235, 233, 228));
        backBtn.setText("Back");
        backBtn.addActionListener(this::backBtnActionPerformed);
        jPanel1.add(backBtn);
        backBtn.setBounds(250, 490, 120, 30);

        itemnameLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        itemnameLabel.setText("Item Name:");
        jPanel1.add(itemnameLabel);
        itemnameLabel.setBounds(250, 100, 90, 17);

        itemnameTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(itemnameTextField);
        itemnameTextField.setBounds(250, 130, 220, 23);

        descriptionLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        descriptionLabel.setText("Description:");
        jPanel1.add(descriptionLabel);
        descriptionLabel.setBounds(250, 170, 100, 17);

        descriptionTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(descriptionTextField);
        descriptionTextField.setBounds(250, 200, 480, 30);

        categoryLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        categoryLabel.setText("Category:");
        jPanel1.add(categoryLabel);
        categoryLabel.setBounds(510, 100, 80, 17);

        categoryDropDown.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        categoryDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(categoryDropDown);
        categoryDropDown.setBounds(510, 130, 220, 23);

        colorLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        colorLabel.setText("Color:");
        jPanel1.add(colorLabel);
        colorLabel.setBounds(250, 250, 70, 17);

        colorTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(colorTextField);
        colorTextField.setBounds(250, 280, 480, 23);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Last Seen Location:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(250, 320, 150, 16);

        lastseenTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(lastseenTextField);
        lastseenTextField.setBounds(250, 350, 480, 23);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Date Lost:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(250, 390, 80, 17);

        datelostTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        jPanel1.add(datelostTextField);
        datelostTextField.setBounds(250, 420, 480, 22);

        submitBtn.setBackground(new java.awt.Color(244, 85, 0));
        submitBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        submitBtn.setForeground(new java.awt.Color(235, 233, 228));
        submitBtn.setText("Submit");
        submitBtn.addActionListener(this::submitBtnActionPerformed);
        jPanel1.add(submitBtn);
        submitBtn.setBounds(610, 490, 120, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
        Dashboard home = new Dashboard();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void browseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_browseBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBtnActionPerformed

    private void userserviceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userserviceBtnActionPerformed
        // TODO add your handling code here:
        UserService userService = new UserService();
        userService.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_userserviceBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        UserService userService = new UserService();
        userService.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        String name = itemnameTextField.getText().trim();
        String description = descriptionTextField.getText().trim();
        String color = colorTextField.getText().trim();
        String locationLost = lastseenTextField.getText().trim();
        String dateLost = datelostTextField.getText().trim();
        
        String selectedCategoryStr = (String) categoryDropDown.getSelectedItem();
        Category selectedCategory = Category.OTHERS;
        
        for(Category cat : Category.values()){
            if(cat.toString().equals(selectedCategoryStr)){
                selectedCategory = cat;
                break;
            }
        }
        
        if(name.isEmpty() || locationLost.isEmpty() || dateLost.isEmpty()){
            JOptionPane.showMessageDialog(this, "Item name, Last Seen Location, and Date Lost cannot be empty.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            LocalDate dateLost2 = LocalDate.parse(dateLost);
            String activeReporterID = "STU-12345";
            Item lostItem = ItemFactory.createItem("LOST", name, description, selectedCategory, color, locationLost, dateLost2, null, activeReporterID);
            
            ItemDA dbAccess = new ItemDA();
            boolean success = dbAccess.insertLostItem((ItemLost)lostItem);
            
            if(success){
                JOptionPane.showMessageDialog(this, "Report sent successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                
                itemnameTextField.setText("");
                descriptionTextField.setText("");
                colorTextField.setText("");
                lastseenTextField.setText("");
                datelostTextField.setText("");
                categoryDropDown.setSelectedIndex(0);
            } else {
                JOptionPane.showMessageDialog(this, "Database entry failed.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch(DateTimeParseException e){
            JOptionPane.showConfirmDialog(this, "Please input your data using format: YYYY-MM-DD", "Date Format Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_submitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReportLostItem().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton browseBtn;
    private javax.swing.JComboBox<String> categoryDropDown;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JLabel colorLabel;
    private javax.swing.JTextField colorTextField;
    private javax.swing.JFormattedTextField datelostTextField;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextField descriptionTextField;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel itemnameLabel;
    private javax.swing.JTextField itemnameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lastseenTextField;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton submitBtn;
    private javax.swing.JButton userserviceBtn;
    // End of variables declaration//GEN-END:variables
}
