/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lostfound.gui;

import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;
import lostfound.model.Category;
import lostfound.model.Item;
import lostfound.model.ItemFound;
import lostfound.da.ItemDA;
import lostfound.model.ItemFactory;
import lostfound.session.SessionManager;
/**
 *
 * @author danis
 */
public class ReportFoundItem extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReportFoundItem.class.getName());

    /**
     * Creates new form ReportFoundItem
     */
    public ReportFoundItem() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        
        categoryDropDown.removeAllItems();
        for(Category cat : Category.values()){
            categoryDropDown.addItem(cat.name());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        categoryDropDown = new javax.swing.JComboBox<>();
        descriptionLabel = new javax.swing.JLabel();
        descriptionTextField = new javax.swing.JTextField();
        colorLabel = new javax.swing.JLabel();
        locationfoundTextField = new javax.swing.JTextField();
        locationfoundLabel = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        submitBtn = new javax.swing.JButton();
        itemnameLabel = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();
        itemnameTextField = new javax.swing.JTextField();
        colorTextField = new javax.swing.JTextField();
        storeatLabel = new javax.swing.JLabel();
        datefoundTextField = new javax.swing.JFormattedTextField();
        datefoundLabel = new javax.swing.JLabel();
        storeatTextField = new javax.swing.JTextField();
        homeBtn = new javax.swing.JButton();
        browseBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        userserviceBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(242, 224, 139));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Bell MT", 1, 48)); // NOI18N
        jLabel3.setText("File a New Found Item Report");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(740, 90, 650, 40);

        categoryDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(categoryDropDown);
        categoryDropDown.setBounds(1110, 250, 220, 30);

        descriptionLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        descriptionLabel.setText("Description:");
        jPanel1.add(descriptionLabel);
        descriptionLabel.setBounds(760, 290, 140, 40);

        descriptionTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(descriptionTextField);
        descriptionTextField.setBounds(760, 330, 580, 30);

        colorLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        colorLabel.setText("Color:");
        jPanel1.add(colorLabel);
        colorLabel.setBounds(760, 370, 70, 30);

        locationfoundTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(locationfoundTextField);
        locationfoundTextField.setBounds(760, 480, 580, 30);

        locationfoundLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        locationfoundLabel.setText("Location Found:");
        jPanel1.add(locationfoundLabel);
        locationfoundLabel.setBounds(760, 450, 180, 28);

        backBtn.setBackground(new java.awt.Color(231, 85, 49));
        backBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(235, 233, 228));
        backBtn.setText("BACK");
        backBtn.addActionListener(this::backBtnActionPerformed);
        jPanel1.add(backBtn);
        backBtn.setBounds(490, 800, 180, 30);

        submitBtn.setBackground(new java.awt.Color(231, 85, 49));
        submitBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        submitBtn.setForeground(new java.awt.Color(235, 233, 228));
        submitBtn.setText("SUBMIT");
        submitBtn.setMaximumSize(new java.awt.Dimension(136, 24));
        submitBtn.setMinimumSize(new java.awt.Dimension(136, 24));
        submitBtn.addActionListener(this::submitBtnActionPerformed);
        jPanel1.add(submitBtn);
        submitBtn.setBounds(1470, 800, 180, 30);

        itemnameLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        itemnameLabel.setText("Item Name:");
        jPanel1.add(itemnameLabel);
        itemnameLabel.setBounds(760, 200, 130, 50);

        categoryLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        categoryLabel.setText("Category:");
        jPanel1.add(categoryLabel);
        categoryLabel.setBounds(1110, 210, 110, 40);

        itemnameTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(itemnameTextField);
        itemnameTextField.setBounds(760, 250, 220, 30);

        colorTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(colorTextField);
        colorTextField.setBounds(760, 400, 580, 30);

        storeatLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        storeatLabel.setText("Store At:");
        jPanel1.add(storeatLabel);
        storeatLabel.setBounds(760, 600, 120, 28);

        datefoundTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        datefoundTextField.setMaximumSize(new java.awt.Dimension(65, 25));
        datefoundTextField.setMinimumSize(new java.awt.Dimension(65, 25));
        jPanel1.add(datefoundTextField);
        datefoundTextField.setBounds(760, 550, 580, 30);

        datefoundLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        datefoundLabel.setText("Date Found: ");
        jPanel1.add(datefoundLabel);
        datefoundLabel.setBounds(760, 520, 150, 28);

        storeatTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        storeatTextField.setPreferredSize(new java.awt.Dimension(65, 25));
        jPanel1.add(storeatTextField);
        storeatTextField.setBounds(760, 630, 580, 30);

        homeBtn.setBackground(new java.awt.Color(231, 85, 49));
        homeBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        homeBtn.setForeground(new java.awt.Color(255, 255, 255));
        homeBtn.setText("HOME");
        homeBtn.addActionListener(this::homeBtnActionPerformed);
        jPanel1.add(homeBtn);
        homeBtn.setBounds(30, 170, 180, 30);

        browseBtn.setBackground(new java.awt.Color(231, 85, 49));
        browseBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        browseBtn.setForeground(new java.awt.Color(255, 255, 255));
        browseBtn.setText("BROWSE");
        browseBtn.addActionListener(this::browseBtnActionPerformed);
        jPanel1.add(browseBtn);
        browseBtn.setBounds(30, 240, 180, 30);

        searchBtn.setBackground(new java.awt.Color(231, 85, 49));
        searchBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setText("SEARCH");
        searchBtn.setToolTipText("");
        searchBtn.addActionListener(this::searchBtnActionPerformed);
        jPanel1.add(searchBtn);
        searchBtn.setBounds(30, 310, 180, 30);

        userserviceBtn.setBackground(new java.awt.Color(231, 85, 49));
        userserviceBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        userserviceBtn.setForeground(new java.awt.Color(255, 255, 255));
        userserviceBtn.setText("USER SERVICE");
        userserviceBtn.setToolTipText("");
        userserviceBtn.setActionCommand("userService");
        userserviceBtn.addActionListener(this::userserviceBtnActionPerformed);
        jPanel1.add(userserviceBtn);
        userserviceBtn.setBounds(30, 380, 180, 30);

        logoutBtn.setBackground(new java.awt.Color(235, 233, 228));
        logoutBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        logoutBtn.setText("LOGOUT");
        logoutBtn.addActionListener(this::logoutBtnActionPerformed);
        jPanel1.add(logoutBtn);
        logoutBtn.setBounds(30, 950, 180, 30);

        jLabel5.setFont(new java.awt.Font("STHupo", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(231, 85, 49));
        jLabel5.setText("Lost&FoundU");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 100, 190, 56);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lostfound/gambar/bluewhitebg.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 240, 1080);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
        Dashboard home = new Dashboard();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void browseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBtnActionPerformed
        // TODO add your handling code here:
        BrowseItems browse = new BrowseItems();
        browse.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_browseBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        SearchItems search = new SearchItems();
        search.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_searchBtnActionPerformed

    private void userserviceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userserviceBtnActionPerformed
        // TODO add your handling code here:
        UserService userService = new UserService();
        userService.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_userserviceBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        SessionManager.getInstance().logout();
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        UserService userService = new UserService();
        userService.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        String name = itemnameTextField.getText().trim();
        String description = descriptionTextField.getText().trim();
        String color = colorTextField.getText().trim();
        String locationFound = locationfoundTextField.getText().trim();
        String dateFoundStr = datefoundTextField.getText().trim();
        String storeAt = storeatTextField.getText().trim();
        
        String selectedCategoryStr = (String) categoryDropDown.getSelectedItem();
        Category selectedCategory = Category.OTHERS;
        for(Category cat : Category.values()){
            if(cat.name().equals(selectedCategoryStr)){
                selectedCategory = cat;
                break;
            }
        }
        
        if(name.isEmpty() || locationFound.isEmpty() || dateFoundStr.isEmpty()){
            JOptionPane.showMessageDialog(this, "Item Name, Location Found, and Date Found cannot be empty.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            LocalDate dateFound = LocalDate.parse(dateFoundStr);
            String reporterID = SessionManager.getInstance().getAccountID();
            if (reporterID == null) {
                JOptionPane.showMessageDialog(this, "Please log in before reporting an item.", "Session Error", JOptionPane.ERROR_MESSAGE);
                Login login = new Login();
                login.setVisible(true);
                this.dispose();
                return;
            }
            
            Item foundItem = ItemFactory.createItem("FOUND", name, description, selectedCategory, color, locationFound, dateFound, storeAt, reporterID);
            
            ItemDA dbAccess = new ItemDA();
            boolean success = dbAccess.insertFoundItem((ItemFound) foundItem);
            
            if(success){
                JOptionPane.showMessageDialog(this, "Found Item report submitted successfully for verification!", "Success", JOptionPane.INFORMATION_MESSAGE);
                
                Dashboard dashboard = new Dashboard();
                dashboard.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Database execution error", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (DateTimeParseException e){
            JOptionPane.showMessageDialog(this, "Please input your date using this format: yyyy-mm-dd", "Date Format Error", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Input Rule Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_submitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReportFoundItem().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton browseBtn;
    private javax.swing.JComboBox<String> categoryDropDown;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JLabel colorLabel;
    private javax.swing.JTextField colorTextField;
    private javax.swing.JLabel datefoundLabel;
    private javax.swing.JFormattedTextField datefoundTextField;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextField descriptionTextField;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel itemnameLabel;
    private javax.swing.JTextField itemnameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel locationfoundLabel;
    private javax.swing.JTextField locationfoundTextField;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JLabel storeatLabel;
    private javax.swing.JTextField storeatTextField;
    private javax.swing.JButton submitBtn;
    private javax.swing.JButton userserviceBtn;
    // End of variables declaration//GEN-END:variables
}
