/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lostfound.gui;

import javax.swing.JOptionPane;
import lostfound.da.ItemDA;
import lostfound.session.SessionManager;

/**
 *
 * @author danis
 */
public class SearchItems extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SearchItems.class.getName());

    /**
     * Creates new form SearchItems
     */
    public SearchItems() {
        initComponents();
        loadAllItems();
    }
    
    private void loadAllItems() {
        ItemDA itemDA = new ItemDA();
        resultsTable.setModel(itemDA.getAllItemsTableModel());
    }
    
    private void searchItems() {
        String keyword = keywordTextField.getText().trim();
        if (keyword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a search keyword.", "Search Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        ItemDA itemDA = new ItemDA();
        resultsTable.setModel(itemDA.searchItemsTableModel(keyword));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        homeBtn = new javax.swing.JButton();
        browseBtn = new javax.swing.JButton();
        searchNavBtn = new javax.swing.JButton();
        userserviceBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        keywordLabel = new javax.swing.JLabel();
        keywordTextField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(235, 233, 228));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 550));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(244, 85, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 550));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Nirmala Text", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(235, 233, 228));
        jLabel4.setText("Lost&FoundU");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 50, 170, 56);

        homeBtn.setBackground(new java.awt.Color(235, 233, 228));
        homeBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        homeBtn.setText("Home");
        homeBtn.addActionListener(this::homeBtnActionPerformed);
        jPanel2.add(homeBtn);
        homeBtn.setBounds(10, 170, 180, 30);

        browseBtn.setBackground(new java.awt.Color(235, 233, 228));
        browseBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        browseBtn.setText("Browse");
        browseBtn.addActionListener(this::browseBtnActionPerformed);
        jPanel2.add(browseBtn);
        browseBtn.setBounds(10, 220, 180, 30);

        searchNavBtn.setBackground(new java.awt.Color(235, 233, 228));
        searchNavBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        searchNavBtn.setText("Search");
        searchNavBtn.setToolTipText("");
        searchNavBtn.addActionListener(this::searchNavBtnActionPerformed);
        jPanel2.add(searchNavBtn);
        searchNavBtn.setBounds(10, 270, 180, 30);

        userserviceBtn.setBackground(new java.awt.Color(235, 233, 228));
        userserviceBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        userserviceBtn.setText("User Service");
        userserviceBtn.setToolTipText("");
        userserviceBtn.addActionListener(this::userserviceBtnActionPerformed);
        jPanel2.add(userserviceBtn);
        userserviceBtn.setBounds(10, 320, 180, 30);

        logoutBtn.setBackground(new java.awt.Color(235, 233, 228));
        logoutBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(this::logoutBtnActionPerformed);
        jPanel2.add(logoutBtn);
        logoutBtn.setBounds(10, 500, 180, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 200, 550);

        titleLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        titleLabel.setText("Search Items");
        jPanel1.add(titleLabel);
        titleLabel.setBounds(230, 50, 150, 22);

        keywordLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        keywordLabel.setText("Keyword:");
        jPanel1.add(keywordLabel);
        keywordLabel.setBounds(230, 100, 80, 17);

        keywordTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        keywordTextField.addActionListener(this::keywordTextFieldActionPerformed);
        jPanel1.add(keywordTextField);
        keywordTextField.setBounds(310, 100, 250, 23);

        searchBtn.setBackground(new java.awt.Color(244, 85, 0));
        searchBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(235, 233, 228));
        searchBtn.setText("Search");
        searchBtn.addActionListener(this::searchBtnActionPerformed);
        jPanel1.add(searchBtn);
        searchBtn.setBounds(580, 95, 85, 30);

        clearBtn.setBackground(new java.awt.Color(244, 85, 0));
        clearBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        clearBtn.setForeground(new java.awt.Color(235, 233, 228));
        clearBtn.setText("Clear");
        clearBtn.addActionListener(this::clearBtnActionPerformed);
        jPanel1.add(clearBtn);
        clearBtn.setBounds(680, 95, 80, 30);

        resultsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(resultsTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(230, 150, 530, 340);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        Dashboard home = new Dashboard();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void browseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBtnActionPerformed
        BrowseItems browse = new BrowseItems();
        browse.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_browseBtnActionPerformed

    private void searchNavBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchNavBtnActionPerformed
        keywordTextField.requestFocus();
    }//GEN-LAST:event_searchNavBtnActionPerformed

    private void userserviceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userserviceBtnActionPerformed
        UserService userService = new UserService();
        userService.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_userserviceBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        SessionManager.getInstance().logout();
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void keywordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keywordTextFieldActionPerformed
        searchItems();
    }//GEN-LAST:event_keywordTextFieldActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        searchItems();
    }//GEN-LAST:event_searchBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        keywordTextField.setText("");
        loadAllItems();
    }//GEN-LAST:event_clearBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(() -> new SearchItems().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel keywordLabel;
    private javax.swing.JTextField keywordTextField;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JTable resultsTable;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton searchNavBtn;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton userserviceBtn;
    // End of variables declaration//GEN-END:variables
}
