
package lostfound.gui;

import javax.swing.JOptionPane;
import lostfound.da.ItemDA;
import lostfound.session.SessionManager;


public class SearchItems extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SearchItems.class.getName());

    /**
     * Creates new form SearchItems
     */
    public SearchItems() {
        initComponents();
        loadAllItems();
    }
    
    private void loadAllItems() {
        ItemDA itemDA = new ItemDA();
        resultsTable.setModel(itemDA.getAllItemsTableModel());
    }
    
    private void searchItems() {
        String keyword = keywordTextField.getText().trim();
        if (keyword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a search keyword.", "Search Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        ItemDA itemDA = new ItemDA();
        resultsTable.setModel(itemDA.searchItemsTableModel(keyword));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        homeBtn1 = new javax.swing.JButton();
        browseBtn1 = new javax.swing.JButton();
        searchBtn1 = new javax.swing.JButton();
        userserviceBtn1 = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        keywordLabel = new javax.swing.JLabel();
        keywordTextField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultsTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(242, 224, 139));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(null);

        jLabel5.setFont(new java.awt.Font("STHupo", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(231, 85, 49));
        jLabel5.setText("Lost&FoundU");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 100, 190, 56);

        homeBtn1.setBackground(new java.awt.Color(231, 85, 49));
        homeBtn1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        homeBtn1.setForeground(new java.awt.Color(255, 255, 255));
        homeBtn1.setText("HOME");
        homeBtn1.addActionListener(this::homeBtn1ActionPerformed);
        jPanel1.add(homeBtn1);
        homeBtn1.setBounds(30, 170, 180, 30);

        browseBtn1.setBackground(new java.awt.Color(231, 85, 49));
        browseBtn1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        browseBtn1.setForeground(new java.awt.Color(255, 255, 255));
        browseBtn1.setText("BROWSE");
        browseBtn1.addActionListener(this::browseBtn1ActionPerformed);
        jPanel1.add(browseBtn1);
        browseBtn1.setBounds(30, 240, 180, 30);

        searchBtn1.setBackground(new java.awt.Color(231, 85, 49));
        searchBtn1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        searchBtn1.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn1.setText("SEARCH");
        searchBtn1.setToolTipText("");
        searchBtn1.addActionListener(this::searchBtn1ActionPerformed);
        jPanel1.add(searchBtn1);
        searchBtn1.setBounds(30, 310, 180, 30);

        userserviceBtn1.setBackground(new java.awt.Color(231, 85, 49));
        userserviceBtn1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        userserviceBtn1.setForeground(new java.awt.Color(255, 255, 255));
        userserviceBtn1.setText("USER SERVICE");
        userserviceBtn1.setToolTipText("");
        userserviceBtn1.setActionCommand("userService");
        userserviceBtn1.addActionListener(this::userserviceBtn1ActionPerformed);
        jPanel1.add(userserviceBtn1);
        userserviceBtn1.setBounds(30, 380, 180, 30);

        titleLabel.setFont(new java.awt.Font("Bell MT", 1, 48)); // NOI18N
        titleLabel.setText("Search Items");
        jPanel1.add(titleLabel);
        titleLabel.setBounds(930, 40, 280, 50);

        keywordLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        keywordLabel.setText("Keyword:");
        jPanel1.add(keywordLabel);
        keywordLabel.setBounds(680, 110, 110, 30);

        keywordTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        keywordTextField.addActionListener(this::keywordTextFieldActionPerformed);
        jPanel1.add(keywordTextField);
        keywordTextField.setBounds(790, 110, 380, 30);

        searchBtn.setBackground(new java.awt.Color(231, 85, 49));
        searchBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(235, 233, 228));
        searchBtn.setText("SEARCH");
        searchBtn.addActionListener(this::searchBtnActionPerformed);
        jPanel1.add(searchBtn);
        searchBtn.setBounds(1180, 110, 150, 30);

        clearBtn.setBackground(new java.awt.Color(231, 85, 49));
        clearBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        clearBtn.setForeground(new java.awt.Color(235, 233, 228));
        clearBtn.setText("CLEAR");
        clearBtn.addActionListener(this::clearBtnActionPerformed);
        jPanel1.add(clearBtn);
        clearBtn.setBounds(1340, 110, 150, 30);

        logoutBtn.setBackground(new java.awt.Color(235, 233, 228));
        logoutBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        logoutBtn.setText("LOGOUT");
        logoutBtn.addActionListener(this::logoutBtnActionPerformed);
        jPanel1.add(logoutBtn);
        logoutBtn.setBounds(30, 950, 180, 30);

        resultsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(resultsTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(420, 200, 1260, 680);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lostfound/gambar/bluewhitebg.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 240, 1080);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keywordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keywordTextFieldActionPerformed
        searchItems();
    }//GEN-LAST:event_keywordTextFieldActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        searchItems();
    }//GEN-LAST:event_searchBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        keywordTextField.setText("");
        loadAllItems();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void homeBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtn1ActionPerformed
        // TODO add your handling code here:
        Dashboard home = new Dashboard();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeBtn1ActionPerformed

    private void browseBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBtn1ActionPerformed
        // TODO add your handling code here:
        BrowseItems browse = new BrowseItems();
        browse.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_browseBtn1ActionPerformed

    private void searchBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtn1ActionPerformed
        // TODO add your handling code here:
        SearchItems search = new SearchItems();
        search.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_searchBtn1ActionPerformed

    private void userserviceBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userserviceBtn1ActionPerformed
        // TODO add your handling code here:
        UserService userService = new UserService();
        userService.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_userserviceBtn1ActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        SessionManager.getInstance().logout();
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(() -> new SearchItems().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseBtn1;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton homeBtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel keywordLabel;
    private javax.swing.JTextField keywordTextField;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JTable resultsTable;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton searchBtn1;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton userserviceBtn1;
    // End of variables declaration//GEN-END:variables
}
