/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lostfound.gui;

import javax.swing.JOptionPane;
import lostfound.db.DBConnection;
import lostfound.da.UserDA;
import lostfound.session.SessionManager;
/**
 *
 * @author danis
 */
public class StaffLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StaffLogin.class.getName());
    private DBConnection connection;
    private UserDA userDA;
    /**
     * Creates new form Login
     */
    public StaffLogin() {
        initComponents();
        
        connection = new DBConnection();
        userDA = new UserDA();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JPasswordField();
        passwordLabel = new javax.swing.JLabel();
        forgotPassword = new javax.swing.JLabel();
        userLogin = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        register = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        staffLogin = new javax.swing.JLabel();
        logostamp = new javax.swing.JLabel();
        bluewhitebg = new javax.swing.JLabel();
        bgpic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(235, 233, 228));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(null);

        emailLabel.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        emailLabel.setText("Email:");
        jPanel1.add(emailLabel);
        emailLabel.setBounds(1010, 420, 60, 21);

        emailTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        emailTextField.addActionListener(this::emailTextFieldActionPerformed);
        jPanel1.add(emailTextField);
        emailTextField.setBounds(1010, 450, 410, 23);

        passwordTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(passwordTextField);
        passwordTextField.setBounds(1010, 520, 410, 23);

        passwordLabel.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        passwordLabel.setText("Password:");
        jPanel1.add(passwordLabel);
        passwordLabel.setBounds(1010, 490, 90, 21);

        forgotPassword.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        forgotPassword.setText("<html><font color=\"blue\"><u>Forgot Password?</u></font></html>");
        forgotPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotPasswordMouseClicked(evt);
            }
        });
        jPanel1.add(forgotPassword);
        forgotPassword.setBounds(1010, 570, 110, 16);

        userLogin.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        userLogin.setText("<html><font color=\"blue\"><u>User Login</u></font></html>");
        userLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userLoginMouseClicked(evt);
            }
        });
        jPanel1.add(userLogin);
        userLogin.setBounds(1350, 570, 70, 16);

        loginBtn.setBackground(new java.awt.Color(244, 85, 0));
        loginBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(235, 233, 228));
        loginBtn.setText("LOGIN");
        loginBtn.addActionListener(this::loginBtnActionPerformed);
        jPanel1.add(loginBtn);
        loginBtn.setBounds(1010, 610, 410, 30);

        register.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        register.setText("<html>Don't have an account? <font color=\"blue\"><u>Register</u></font></html>");
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerMouseClicked(evt);
            }
        });
        jPanel1.add(register);
        register.setBounds(1010, 660, 190, 30);

        title.setFont(new java.awt.Font("STHupo", 1, 60)); // NOI18N
        title.setForeground(new java.awt.Color(231, 85, 49));
        title.setText("lost&foundU");
        jPanel1.add(title);
        title.setBounds(190, 470, 360, 62);

        staffLogin.setBackground(new java.awt.Color(0, 0, 0));
        staffLogin.setFont(new java.awt.Font("Bell MT", 1, 48)); // NOI18N
        staffLogin.setText("Staff Login");
        jPanel1.add(staffLogin);
        staffLogin.setBounds(1010, 330, 250, 54);

        logostamp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lostfound/gambar/logostampp.png"))); // NOI18N
        jPanel1.add(logostamp);
        logostamp.setBounds(1560, 40, 320, 390);

        bluewhitebg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bluewhitebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lostfound/gambar/bluewhitebg.png"))); // NOI18N
        jPanel1.add(bluewhitebg);
        bluewhitebg.setBounds(730, 0, 1190, 1080);

        bgpic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bgpic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lostfound/gambar/bgpic.jpg"))); // NOI18N
        jPanel1.add(bgpic);
        bgpic.setBounds(0, 0, 730, 1080);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        String email = emailTextField.getText().trim();
        String password = new String(passwordTextField.getPassword()).trim();

        //input field validation
        if(email.isEmpty() || password.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please fill in all the fields!", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        //query
        int loginResult = userDA.loginUser(email, password);

        switch (loginResult){
            case 1:
            String[] sessionUser = userDA.getUserSessionByEmail(email);
            if (sessionUser == null) {
                JOptionPane.showMessageDialog(this, "Login successful, but user session could not be loaded.", "System Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            SessionManager.getInstance().loginDatabaseUser(sessionUser[0], sessionUser[1], sessionUser[2]);
            JOptionPane.showMessageDialog(this, "Login Succesful!\nWelcome Back, " + sessionUser[1] + ".", "Success", JOptionPane.INFORMATION_MESSAGE);

            Dashboard dashboard = new Dashboard();
            dashboard.setVisible(true);
            this.dispose();
            break;

            case 0:
            JOptionPane.showMessageDialog(this, "The email address entered does not exist in our database.", "Login Failed", JOptionPane.ERROR_MESSAGE);
            break;

            case -1:
            JOptionPane.showMessageDialog(this, "Incorrect password! Please try again.", "Login Failed", JOptionPane.ERROR_MESSAGE);
            passwordTextField.setText("");
            passwordTextField.requestFocus();
            break;

            default:
            JOptionPane.showMessageDialog(this, "An unexpected error occured while while connecting to the database.", "System Error", JOptionPane.ERROR_MESSAGE);
            break;
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void forgotPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotPasswordMouseClicked
        // TODO add your handling code here:
        ForgotPassword pass = new ForgotPassword();
        pass.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_forgotPasswordMouseClicked

    private void userLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userLoginMouseClicked
        // TODO add your handling code here:
        StaffLogin staffLogin = new StaffLogin();
        staffLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_userLoginMouseClicked

    private void registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseClicked
        // TODO add your handling code here:
        Register register = new Register();
        register.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StaffLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgpic;
    private javax.swing.JLabel bluewhitebg;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel forgotPassword;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel logostamp;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JLabel register;
    private javax.swing.JLabel staffLogin;
    private javax.swing.JLabel title;
    private javax.swing.JLabel userLogin;
    // End of variables declaration//GEN-END:variables
}
