/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lostfound.gui;

import javax.swing.JOptionPane;
import lostfound.da.ClaimDA;
import lostfound.da.ItemDA;
import lostfound.session.SessionManager;

/**
 *
 * @author danis
 */
public class StaffDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StaffDashboard.class.getName());
    private boolean viewingClaims = true;

    /**
     * Creates new form StaffDashboard
     */
    public StaffDashboard() {
        initComponents();
        loadClaims();
    }
    
    private void loadClaims() {
        if (!"Staff".equals(SessionManager.getInstance().getRole())) {
            JOptionPane.showMessageDialog(this, "Please log in as staff.", "Session Error", JOptionPane.ERROR_MESSAGE);
            StaffLogin staffLogin = new StaffLogin();
            staffLogin.setVisible(true);
            this.dispose();
            return;
        }
        
        ClaimDA claimDA = new ClaimDA();
        claimsTable.setModel(claimDA.getAllClaimsTableModel());
        titleLabel.setText("Staff Dashboard - Claims");
        viewingClaims = true;
        approveBtn.setVisible(true);
        rejectBtn.setVisible(true);
        verifyBtn.setVisible(false);
    }

    private void loadFoundItems() {
        if (!"Staff".equals(SessionManager.getInstance().getRole())) {
            JOptionPane.showMessageDialog(this, "Please log in as staff.", "Session Error", JOptionPane.ERROR_MESSAGE);
            StaffLogin staffLogin = new StaffLogin();
            staffLogin.setVisible(true);
            this.dispose();
            return;
        }
        
        ItemDA itemDA = new ItemDA();
        claimsTable.setModel(itemDA.getFoundItemsTableModel());
        titleLabel.setText("Staff Dashboard - Found Items");
        viewingClaims = false;
        approveBtn.setVisible(false);
        rejectBtn.setVisible(false);
        verifyBtn.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        refreshBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        claimsTable = new javax.swing.JTable();
        approveBtn = new javax.swing.JButton();
        rejectBtn = new javax.swing.JButton();
        verifyBtn = new javax.swing.JButton();
        claimsBtn = new javax.swing.JButton();
        foundItemsBtn = new javax.swing.JButton();
        logoutBtn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(242, 224, 139));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(null);

        jLabel5.setFont(new java.awt.Font("STHupo", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(231, 85, 49));
        jLabel5.setText("Lost&FoundU");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 100, 190, 56);

        titleLabel.setFont(new java.awt.Font("Bell MT", 1, 48)); // NOI18N
        titleLabel.setText("Staff Dashboard - Claims");
        jPanel1.add(titleLabel);
        titleLabel.setBounds(790, 80, 670, 80);

        refreshBtn.setBackground(new java.awt.Color(231, 85, 49));
        refreshBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        refreshBtn.setForeground(new java.awt.Color(235, 233, 228));
        refreshBtn.setText("REFRESH");
        refreshBtn.addActionListener(this::refreshBtnActionPerformed);
        jPanel1.add(refreshBtn);
        refreshBtn.setBounds(1480, 90, 150, 50);

        claimsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(claimsTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(480, 180, 1150, 660);

        approveBtn.setBackground(new java.awt.Color(231, 85, 49));
        approveBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        approveBtn.setForeground(new java.awt.Color(235, 233, 228));
        approveBtn.setText("APPROVE");
        approveBtn.addActionListener(this::approveBtnActionPerformed);
        jPanel1.add(approveBtn);
        approveBtn.setBounds(1660, 510, 150, 50);

        rejectBtn.setBackground(new java.awt.Color(231, 85, 49));
        rejectBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rejectBtn.setForeground(new java.awt.Color(235, 233, 228));
        rejectBtn.setText("REJECT");
        rejectBtn.addActionListener(this::rejectBtnActionPerformed);
        jPanel1.add(rejectBtn);
        rejectBtn.setBounds(1660, 600, 150, 50);

        verifyBtn.setBackground(new java.awt.Color(231, 85, 49));
        verifyBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        verifyBtn.setForeground(new java.awt.Color(235, 233, 228));
        verifyBtn.setText("VERIFY ITEM");
        verifyBtn.addActionListener(this::verifyBtnActionPerformed);
        jPanel1.add(verifyBtn);
        verifyBtn.setBounds(1660, 410, 150, 50);

        claimsBtn.setBackground(new java.awt.Color(231, 85, 49));
        claimsBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        claimsBtn.setForeground(new java.awt.Color(255, 255, 255));
        claimsBtn.setText("CLAIMS");
        claimsBtn.addActionListener(this::claimsBtnActionPerformed);
        jPanel1.add(claimsBtn);
        claimsBtn.setBounds(30, 220, 180, 30);

        foundItemsBtn.setBackground(new java.awt.Color(231, 85, 49));
        foundItemsBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        foundItemsBtn.setForeground(new java.awt.Color(255, 255, 255));
        foundItemsBtn.setText("FOUND ITEMS");
        foundItemsBtn.addActionListener(this::foundItemsBtnActionPerformed);
        jPanel1.add(foundItemsBtn);
        foundItemsBtn.setBounds(30, 300, 180, 30);

        logoutBtn1.setBackground(new java.awt.Color(235, 233, 228));
        logoutBtn1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        logoutBtn1.setText("LOGOUT");
        logoutBtn1.addActionListener(this::logoutBtn1ActionPerformed);
        jPanel1.add(logoutBtn1);
        logoutBtn1.setBounds(30, 950, 180, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lostfound/gambar/bluewhitebg.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 240, 1080);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void claimsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claimsBtnActionPerformed
        loadClaims();
    }//GEN-LAST:event_claimsBtnActionPerformed

    private void foundItemsBtnActionPerformed(java.awt.event.ActionEvent evt) {
        loadFoundItems();
    }

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        if (viewingClaims) {
            loadClaims();
        } else {
            loadFoundItems();
        }
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void logoutBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtn1ActionPerformed
        // TODO add your handling code here:
        SessionManager.getInstance().logout();
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutBtn1ActionPerformed

    private void approveBtnActionPerformed(java.awt.event.ActionEvent evt) {
        if (!viewingClaims) {
            return;
        }
        int selectedRow = claimsTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a claim to approve.", "Selection Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String claimID = claimsTable.getValueAt(selectedRow, 0).toString();
        String foundItemID = claimsTable.getValueAt(selectedRow, 2).toString();
        
        int confirm = JOptionPane.showConfirmDialog(this, "Approve claim " + claimID + "?", "Confirm Approval", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        
        ClaimDA claimDA = new ClaimDA();
        boolean success = claimDA.approveClaim(claimID, foundItemID);
        
        if (success) {
            JOptionPane.showMessageDialog(this, "Claim approved successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
            loadClaims();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to approve claim.", "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void rejectBtnActionPerformed(java.awt.event.ActionEvent evt) {
        if (!viewingClaims) {
            return;
        }
        int selectedRow = claimsTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a claim to reject.", "Selection Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String claimID = claimsTable.getValueAt(selectedRow, 0).toString();
        String reason = JOptionPane.showInputDialog(this, "Reason for rejection:");
        
        if (reason == null) {
            return;
        }
        
        reason = reason.trim();
        if (reason.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Rejection reason cannot be empty.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        ClaimDA claimDA = new ClaimDA();
        boolean success = claimDA.rejectClaim(claimID, reason);
        
        if (success) {
            JOptionPane.showMessageDialog(this, "Claim rejected successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
            loadClaims();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to reject claim.", "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void verifyBtnActionPerformed(java.awt.event.ActionEvent evt) {
        if (viewingClaims) {
            return;
        }
        
        int selectedRow = claimsTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a found item to verify.", "Selection Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String itemID = claimsTable.getValueAt(selectedRow, 0).toString();
        String status = claimsTable.getValueAt(selectedRow, 6).toString();
        
        if (!"SUBMITTED".equals(status)) {
            JOptionPane.showMessageDialog(this, "Only SUBMITTED found items can be verified.", "Verify Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this, "Verify found item " + itemID + "?", "Confirm Verification", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        
        ItemDA itemDA = new ItemDA();
        boolean success = itemDA.verifyFoundItem(itemID);
        
        if (success) {
            JOptionPane.showMessageDialog(this, "Found item verified successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
            loadFoundItems();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to verify item. It may already be verified or claimed.", "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(() -> new StaffDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveBtn;
    private javax.swing.JButton claimsBtn;
    private javax.swing.JTable claimsTable;
    private javax.swing.JButton foundItemsBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutBtn1;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton rejectBtn;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton verifyBtn;
    // End of variables declaration//GEN-END:variables
}
