/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lostfound.gui;

import javax.swing.JOptionPane;
import lostfound.da.ClaimDA;
import lostfound.da.ItemDA;
import lostfound.session.SessionManager;

/**
 *
 * @author danis
 */
public class StaffDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StaffDashboard.class.getName());
    private boolean viewingClaims = true;

    /**
     * Creates new form StaffDashboard
     */
    public StaffDashboard() {
        initComponents();
        loadClaims();
    }
    
    private void loadClaims() {
        if (!"Staff".equals(SessionManager.getInstance().getRole())) {
            JOptionPane.showMessageDialog(this, "Please log in as staff.", "Session Error", JOptionPane.ERROR_MESSAGE);
            StaffLogin staffLogin = new StaffLogin();
            staffLogin.setVisible(true);
            this.dispose();
            return;
        }
        
        ClaimDA claimDA = new ClaimDA();
        claimsTable.setModel(claimDA.getAllClaimsTableModel());
        titleLabel.setText("Staff Dashboard - Claims");
        viewingClaims = true;
        approveBtn.setVisible(true);
        rejectBtn.setVisible(true);
        verifyBtn.setVisible(false);
    }

    private void loadFoundItems() {
        if (!"Staff".equals(SessionManager.getInstance().getRole())) {
            JOptionPane.showMessageDialog(this, "Please log in as staff.", "Session Error", JOptionPane.ERROR_MESSAGE);
            StaffLogin staffLogin = new StaffLogin();
            staffLogin.setVisible(true);
            this.dispose();
            return;
        }
        
        ItemDA itemDA = new ItemDA();
        claimsTable.setModel(itemDA.getFoundItemsTableModel());
        titleLabel.setText("Staff Dashboard - Found Items");
        viewingClaims = false;
        approveBtn.setVisible(false);
        rejectBtn.setVisible(false);
        verifyBtn.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        claimsBtn = new javax.swing.JButton();
        foundItemsBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        refreshBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        claimsTable = new javax.swing.JTable();
        approveBtn = new javax.swing.JButton();
        rejectBtn = new javax.swing.JButton();
        verifyBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(235, 233, 228));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 550));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(244, 85, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 550));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Nirmala Text", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(235, 233, 228));
        jLabel4.setText("Lost&FoundU");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 50, 170, 56);

        claimsBtn.setBackground(new java.awt.Color(235, 233, 228));
        claimsBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        claimsBtn.setText("Claims");
        claimsBtn.addActionListener(this::claimsBtnActionPerformed);
        jPanel2.add(claimsBtn);
        claimsBtn.setBounds(10, 170, 180, 30);

        foundItemsBtn.setBackground(new java.awt.Color(235, 233, 228));
        foundItemsBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        foundItemsBtn.setText("Found Items");
        foundItemsBtn.addActionListener(this::foundItemsBtnActionPerformed);
        jPanel2.add(foundItemsBtn);
        foundItemsBtn.setBounds(10, 220, 180, 30);

        logoutBtn.setBackground(new java.awt.Color(235, 233, 228));
        logoutBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(this::logoutBtnActionPerformed);
        jPanel2.add(logoutBtn);
        logoutBtn.setBounds(10, 500, 180, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 200, 550);

        titleLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        titleLabel.setText("Staff Dashboard - Claims");
        jPanel1.add(titleLabel);
        titleLabel.setBounds(230, 50, 240, 22);

        refreshBtn.setBackground(new java.awt.Color(244, 85, 0));
        refreshBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        refreshBtn.setForeground(new java.awt.Color(235, 233, 228));
        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(this::refreshBtnActionPerformed);
        jPanel1.add(refreshBtn);
        refreshBtn.setBounds(650, 50, 110, 30);

        claimsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(claimsTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(230, 100, 530, 340);

        approveBtn.setBackground(new java.awt.Color(244, 85, 0));
        approveBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        approveBtn.setForeground(new java.awt.Color(235, 233, 228));
        approveBtn.setText("Approve");
        approveBtn.addActionListener(this::approveBtnActionPerformed);
        jPanel1.add(approveBtn);
        approveBtn.setBounds(500, 460, 120, 30);

        rejectBtn.setBackground(new java.awt.Color(244, 85, 0));
        rejectBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rejectBtn.setForeground(new java.awt.Color(235, 233, 228));
        rejectBtn.setText("Reject");
        rejectBtn.addActionListener(this::rejectBtnActionPerformed);
        jPanel1.add(rejectBtn);
        rejectBtn.setBounds(640, 460, 120, 30);

        verifyBtn.setBackground(new java.awt.Color(244, 85, 0));
        verifyBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        verifyBtn.setForeground(new java.awt.Color(235, 233, 228));
        verifyBtn.setText("Verify Item");
        verifyBtn.addActionListener(this::verifyBtnActionPerformed);
        jPanel1.add(verifyBtn);
        verifyBtn.setBounds(640, 460, 120, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void claimsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claimsBtnActionPerformed
        loadClaims();
    }//GEN-LAST:event_claimsBtnActionPerformed

    private void foundItemsBtnActionPerformed(java.awt.event.ActionEvent evt) {
        loadFoundItems();
    }

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        SessionManager.getInstance().logout();
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        if (viewingClaims) {
            loadClaims();
        } else {
            loadFoundItems();
        }
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void approveBtnActionPerformed(java.awt.event.ActionEvent evt) {
        if (!viewingClaims) {
            return;
        }
        int selectedRow = claimsTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a claim to approve.", "Selection Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String claimID = claimsTable.getValueAt(selectedRow, 0).toString();
        String foundItemID = claimsTable.getValueAt(selectedRow, 2).toString();
        
        int confirm = JOptionPane.showConfirmDialog(this, "Approve claim " + claimID + "?", "Confirm Approval", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        
        ClaimDA claimDA = new ClaimDA();
        boolean success = claimDA.approveClaim(claimID, foundItemID);
        
        if (success) {
            JOptionPane.showMessageDialog(this, "Claim approved successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
            loadClaims();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to approve claim.", "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void rejectBtnActionPerformed(java.awt.event.ActionEvent evt) {
        if (!viewingClaims) {
            return;
        }
        int selectedRow = claimsTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a claim to reject.", "Selection Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String claimID = claimsTable.getValueAt(selectedRow, 0).toString();
        String reason = JOptionPane.showInputDialog(this, "Reason for rejection:");
        
        if (reason == null) {
            return;
        }
        
        reason = reason.trim();
        if (reason.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Rejection reason cannot be empty.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        ClaimDA claimDA = new ClaimDA();
        boolean success = claimDA.rejectClaim(claimID, reason);
        
        if (success) {
            JOptionPane.showMessageDialog(this, "Claim rejected successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
            loadClaims();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to reject claim.", "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void verifyBtnActionPerformed(java.awt.event.ActionEvent evt) {
        if (viewingClaims) {
            return;
        }
        
        int selectedRow = claimsTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a found item to verify.", "Selection Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String itemID = claimsTable.getValueAt(selectedRow, 0).toString();
        String status = claimsTable.getValueAt(selectedRow, 6).toString();
        
        if (!"SUBMITTED".equals(status)) {
            JOptionPane.showMessageDialog(this, "Only SUBMITTED found items can be verified.", "Verify Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this, "Verify found item " + itemID + "?", "Confirm Verification", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        
        ItemDA itemDA = new ItemDA();
        boolean success = itemDA.verifyFoundItem(itemID);
        
        if (success) {
            JOptionPane.showMessageDialog(this, "Found item verified successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
            loadFoundItems();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to verify item. It may already be verified or claimed.", "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(() -> new StaffDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton claimsBtn;
    private javax.swing.JTable claimsTable;
    private javax.swing.JButton foundItemsBtn;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton approveBtn;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton rejectBtn;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton verifyBtn;
    // End of variables declaration//GEN-END:variables
}
