/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lostfound.gui;

import javax.swing.JOptionPane;
import lostfound.db.DBConnection;
import lostfound.da.StaffDA;
/**
 *
 * @author danis
 */
public class StaffLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StaffLogin.class.getName());
    private DBConnection connection;
    private StaffDA staffDA;
    /**
     * Creates new form StaffLogin
     */
    public StaffLogin() {
        initComponents();
        
        connection = new DBConnection();
        staffDA = new StaffDA();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        staffloginLabel = new javax.swing.JLabel();
        staffidLabel = new javax.swing.JLabel();
        staffidTextField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JPasswordField();
        backtologinLink = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(235, 233, 228));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 550));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(244, 85, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(270, 550));
        jPanel2.setLayout(null);

        staffloginLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        staffloginLabel.setForeground(new java.awt.Color(235, 233, 228));
        staffloginLabel.setText("Staff Login");
        jPanel2.add(staffloginLabel);
        staffloginLabel.setBounds(70, 260, 130, 28);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 270, 550);

        staffidLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        staffidLabel.setText("Staff ID:");
        jPanel1.add(staffidLabel);
        staffidLabel.setBounds(330, 200, 70, 17);

        staffidTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(staffidTextField);
        staffidTextField.setBounds(330, 230, 410, 23);

        passwordLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        passwordLabel.setText("Password:");
        jPanel1.add(passwordLabel);
        passwordLabel.setBounds(330, 280, 90, 17);

        passwordTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(passwordTextField);
        passwordTextField.setBounds(330, 310, 410, 23);

        backtologinLink.setText("<html><font color=\"blue\"><u>Back to login</u></font></html>");
        backtologinLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backtologinLinkMouseClicked(evt);
            }
        });
        jPanel1.add(backtologinLink);
        backtologinLink.setBounds(500, 400, 80, 16);

        loginBtn.setBackground(new java.awt.Color(244, 85, 0));
        loginBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(235, 233, 228));
        loginBtn.setText("Login");
        loginBtn.addActionListener(this::loginBtnActionPerformed);
        jPanel1.add(loginBtn);
        loginBtn.setBounds(330, 360, 410, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        String id = staffidTextField.getText().trim();
        String password = new String(passwordTextField.getPassword()).trim();
        
        if(id.isEmpty() || password.isEmpty()){
            JOptionPane.showMessageDialog(this, "Fields cannot be empty!", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int result = staffDA.staffLogin(id, password);
        
        if(result == 1){
            JOptionPane.showMessageDialog(this, "Login Successful!");
            
//            staffDashboard staffDash = new staffDashboard();
//            staffDash.setVisible(true);
//            this.dispose();
        } else if (result == -1){
            JOptionPane.showMessageDialog(this, "Incorrect password.", "Login Failed", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Staff account does not exist.", "Login Failed", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void backtologinLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backtologinLinkMouseClicked
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backtologinLinkMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StaffLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backtologinLink;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JLabel staffidLabel;
    private javax.swing.JTextField staffidTextField;
    private javax.swing.JLabel staffloginLabel;
    // End of variables declaration//GEN-END:variables
}
