
package lostfound.gui;

import javax.swing.JOptionPane;
import lostfound.da.ClaimDA;
import lostfound.da.ItemDA;
import lostfound.model.ClaimRequest;
import lostfound.session.SessionManager;


public class SubmitClaim extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SubmitClaim.class.getName());

    /**
     * Creates new form SubmitClaim
     */
    public SubmitClaim() {
        initComponents();
        loadFoundItems();
    }

    private void loadFoundItems() {
        ItemDA itemDA = new ItemDA();
        foundItemsTable.setModel(itemDA.getFoundItemsTableModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        homeBtn1 = new javax.swing.JButton();
        browseBtn1 = new javax.swing.JButton();
        searchBtn1 = new javax.swing.JButton();
        userserviceBtn1 = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        foundItemIDLabel = new javax.swing.JLabel();
        foundItemIDTextField = new javax.swing.JTextField();
        proofLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        proofTextArea = new javax.swing.JTextArea();
        foundItemsLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        foundItemsTable = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        submitBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(242, 224, 139));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(null);

        jLabel5.setFont(new java.awt.Font("STHupo", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(231, 85, 49));
        jLabel5.setText("Lost&FoundU");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 100, 190, 56);

        homeBtn1.setBackground(new java.awt.Color(231, 85, 49));
        homeBtn1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        homeBtn1.setForeground(new java.awt.Color(255, 255, 255));
        homeBtn1.setText("HOME");
        homeBtn1.addActionListener(this::homeBtn1ActionPerformed);
        jPanel1.add(homeBtn1);
        homeBtn1.setBounds(30, 170, 180, 30);

        browseBtn1.setBackground(new java.awt.Color(231, 85, 49));
        browseBtn1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        browseBtn1.setForeground(new java.awt.Color(255, 255, 255));
        browseBtn1.setText("BROWSE");
        browseBtn1.addActionListener(this::browseBtn1ActionPerformed);
        jPanel1.add(browseBtn1);
        browseBtn1.setBounds(30, 240, 180, 30);

        searchBtn1.setBackground(new java.awt.Color(231, 85, 49));
        searchBtn1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        searchBtn1.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn1.setText("SEARCH");
        searchBtn1.setToolTipText("");
        searchBtn1.addActionListener(this::searchBtn1ActionPerformed);
        jPanel1.add(searchBtn1);
        searchBtn1.setBounds(30, 310, 180, 30);

        userserviceBtn1.setBackground(new java.awt.Color(231, 85, 49));
        userserviceBtn1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        userserviceBtn1.setForeground(new java.awt.Color(255, 255, 255));
        userserviceBtn1.setText("USER SERVICE");
        userserviceBtn1.setToolTipText("");
        userserviceBtn1.setActionCommand("userService");
        userserviceBtn1.addActionListener(this::userserviceBtn1ActionPerformed);
        jPanel1.add(userserviceBtn1);
        userserviceBtn1.setBounds(30, 380, 180, 30);

        titleLabel.setFont(new java.awt.Font("Bell MT", 1, 48)); // NOI18N
        titleLabel.setText("Submit Claim");
        jPanel1.add(titleLabel);
        titleLabel.setBounds(950, 100, 300, 60);

        foundItemIDLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        foundItemIDLabel.setText("Found Item ID:");
        jPanel1.add(foundItemIDLabel);
        foundItemIDLabel.setBounds(1000, 200, 160, 30);

        foundItemIDTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(foundItemIDTextField);
        foundItemIDTextField.setBounds(750, 240, 670, 30);

        proofLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        proofLabel.setText("Proof of Ownership:");
        jPanel1.add(proofLabel);
        proofLabel.setBounds(640, 290, 220, 30);

        proofTextArea.setColumns(20);
        proofTextArea.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        proofTextArea.setRows(5);
        jScrollPane1.setViewportView(proofTextArea);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(640, 330, 870, 200);

        foundItemsLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        foundItemsLabel.setText("Available Found Items:");
        jPanel1.add(foundItemsLabel);
        foundItemsLabel.setBounds(640, 530, 250, 50);

        foundItemsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        foundItemsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                foundItemsTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(foundItemsTable);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(640, 580, 870, 360);

        backBtn.setBackground(new java.awt.Color(231, 85, 49));
        backBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(235, 233, 228));
        backBtn.setText("BACK");
        backBtn.addActionListener(this::backBtnActionPerformed);
        jPanel1.add(backBtn);
        backBtn.setBounds(640, 970, 180, 30);

        submitBtn.setBackground(new java.awt.Color(231, 85, 49));
        submitBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        submitBtn.setForeground(new java.awt.Color(235, 233, 228));
        submitBtn.setText("SUBMIT");
        submitBtn.addActionListener(this::submitBtnActionPerformed);
        jPanel1.add(submitBtn);
        submitBtn.setBounds(1330, 970, 180, 30);

        logoutBtn.setBackground(new java.awt.Color(235, 233, 228));
        logoutBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        logoutBtn.setText("LOGOUT");
        logoutBtn.addActionListener(this::logoutBtnActionPerformed);
        jPanel1.add(logoutBtn);
        logoutBtn.setBounds(30, 950, 180, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lostfound/gambar/bluewhitebg.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 240, 1080);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        UserService userService = new UserService();
        userService.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        String userID = SessionManager.getInstance().getAccountID();
        String foundItemID = foundItemIDTextField.getText().trim();
        String proof = proofTextArea.getText().trim();
        
        if (userID == null) {
            JOptionPane.showMessageDialog(this, "Please log in before submitting a claim.", "Session Error", JOptionPane.ERROR_MESSAGE);
            Login login = new Login();
            login.setVisible(true);
            this.dispose();
            return;
        }
        
        if (foundItemID.isEmpty() || proof.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Found Item ID and proof cannot be empty.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        ClaimDA claimDA = new ClaimDA();
        if (!claimDA.isClaimableFoundItem(foundItemID)) {
            JOptionPane.showMessageDialog(this, "Found item ID does not exist or is not a found item.", "Claim Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        ClaimRequest claim = new ClaimRequest(userID, foundItemID, null, proof);
        boolean success = claimDA.insertClaim(claim);
        
        if (success) {
            JOptionPane.showMessageDialog(this, "Claim submitted successfully!\nClaim ID: " + claim.getClaimID(), "Success", JOptionPane.INFORMATION_MESSAGE);
            Dashboard dashboard = new Dashboard();
            dashboard.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to submit claim. Please try again.", "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_submitBtnActionPerformed

    private void homeBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtn1ActionPerformed
        // TODO add your handling code here:
        Dashboard home = new Dashboard();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeBtn1ActionPerformed

    private void browseBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBtn1ActionPerformed
        // TODO add your handling code here:
        BrowseItems browse = new BrowseItems();
        browse.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_browseBtn1ActionPerformed

    private void searchBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtn1ActionPerformed
        // TODO add your handling code here:
        SearchItems search = new SearchItems();
        search.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_searchBtn1ActionPerformed

    private void userserviceBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userserviceBtn1ActionPerformed
        // TODO add your handling code here:
        UserService userService = new UserService();
        userService.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_userserviceBtn1ActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        SessionManager.getInstance().logout();
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void foundItemsTableMouseClicked(java.awt.event.MouseEvent evt) {
        int selectedRow = foundItemsTable.getSelectedRow();
        if (selectedRow >= 0) {
            Object itemID = foundItemsTable.getValueAt(selectedRow, 0);
            if (itemID != null) {
                foundItemIDTextField.setText(itemID.toString());
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(() -> new SubmitClaim().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton browseBtn1;
    private javax.swing.JLabel foundItemIDLabel;
    private javax.swing.JTextField foundItemIDTextField;
    private javax.swing.JLabel foundItemsLabel;
    private javax.swing.JTable foundItemsTable;
    private javax.swing.JButton homeBtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JLabel proofLabel;
    private javax.swing.JTextArea proofTextArea;
    private javax.swing.JButton searchBtn1;
    private javax.swing.JButton submitBtn;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton userserviceBtn1;
    // End of variables declaration//GEN-END:variables
}
