/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lostfound.gui;

import javax.swing.JOptionPane;
import lostfound.da.ClaimDA;
import lostfound.da.ItemDA;
import lostfound.model.ClaimRequest;
import lostfound.session.SessionManager;

/**
 *
 * @author danis
 */
public class SubmitClaim extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SubmitClaim.class.getName());

    /**
     * Creates new form SubmitClaim
     */
    public SubmitClaim() {
        initComponents();
        loadFoundItems();
    }

    private void loadFoundItems() {
        ItemDA itemDA = new ItemDA();
        foundItemsTable.setModel(itemDA.getFoundItemsTableModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        homeBtn = new javax.swing.JButton();
        browseBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        userserviceBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        foundItemIDLabel = new javax.swing.JLabel();
        foundItemIDTextField = new javax.swing.JTextField();
        proofLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        proofTextArea = new javax.swing.JTextArea();
        foundItemsLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        foundItemsTable = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        submitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(235, 233, 228));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 550));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(244, 85, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 550));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Nirmala Text", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(235, 233, 228));
        jLabel4.setText("Lost&FoundU");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 50, 170, 56);

        homeBtn.setBackground(new java.awt.Color(235, 233, 228));
        homeBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        homeBtn.setText("Home");
        homeBtn.addActionListener(this::homeBtnActionPerformed);
        jPanel2.add(homeBtn);
        homeBtn.setBounds(10, 170, 180, 30);

        browseBtn.setBackground(new java.awt.Color(235, 233, 228));
        browseBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        browseBtn.setText("Browse");
        browseBtn.addActionListener(this::browseBtnActionPerformed);
        jPanel2.add(browseBtn);
        browseBtn.setBounds(10, 220, 180, 30);

        searchBtn.setBackground(new java.awt.Color(235, 233, 228));
        searchBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        searchBtn.setText("Search");
        searchBtn.setToolTipText("");
        searchBtn.addActionListener(this::searchBtnActionPerformed);
        jPanel2.add(searchBtn);
        searchBtn.setBounds(10, 270, 180, 30);

        userserviceBtn.setBackground(new java.awt.Color(235, 233, 228));
        userserviceBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        userserviceBtn.setText("User Service");
        userserviceBtn.setToolTipText("");
        userserviceBtn.addActionListener(this::userserviceBtnActionPerformed);
        jPanel2.add(userserviceBtn);
        userserviceBtn.setBounds(10, 320, 180, 30);

        logoutBtn.setBackground(new java.awt.Color(235, 233, 228));
        logoutBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(this::logoutBtnActionPerformed);
        jPanel2.add(logoutBtn);
        logoutBtn.setBounds(10, 500, 180, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 200, 550);

        titleLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        titleLabel.setText("Submit Claim");
        jPanel1.add(titleLabel);
        titleLabel.setBounds(230, 30, 150, 22);

        foundItemIDLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        foundItemIDLabel.setText("Found Item ID:");
        jPanel1.add(foundItemIDLabel);
        foundItemIDLabel.setBounds(250, 80, 120, 17);

        foundItemIDTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(foundItemIDTextField);
        foundItemIDTextField.setBounds(250, 110, 480, 23);

        proofLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        proofLabel.setText("Proof of Ownership:");
        jPanel1.add(proofLabel);
        proofLabel.setBounds(250, 150, 170, 17);

        proofTextArea.setColumns(20);
        proofTextArea.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        proofTextArea.setRows(5);
        jScrollPane1.setViewportView(proofTextArea);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(250, 180, 480, 90);

        foundItemsLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        foundItemsLabel.setText("Available Found Items:");
        jPanel1.add(foundItemsLabel);
        foundItemsLabel.setBounds(250, 290, 170, 17);

        foundItemsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        foundItemsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                foundItemsTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(foundItemsTable);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(250, 320, 480, 110);

        backBtn.setBackground(new java.awt.Color(244, 85, 0));
        backBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(235, 233, 228));
        backBtn.setText("Back");
        backBtn.addActionListener(this::backBtnActionPerformed);
        jPanel1.add(backBtn);
        backBtn.setBounds(250, 460, 120, 30);

        submitBtn.setBackground(new java.awt.Color(244, 85, 0));
        submitBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        submitBtn.setForeground(new java.awt.Color(235, 233, 228));
        submitBtn.setText("Submit");
        submitBtn.addActionListener(this::submitBtnActionPerformed);
        jPanel1.add(submitBtn);
        submitBtn.setBounds(610, 460, 120, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        Dashboard home = new Dashboard();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void browseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBtnActionPerformed
        BrowseItems browse = new BrowseItems();
        browse.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_browseBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        SearchItems search = new SearchItems();
        search.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_searchBtnActionPerformed

    private void userserviceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userserviceBtnActionPerformed
        UserService userService = new UserService();
        userService.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_userserviceBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        SessionManager.getInstance().logout();
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        UserService userService = new UserService();
        userService.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        String userID = SessionManager.getInstance().getAccountID();
        String foundItemID = foundItemIDTextField.getText().trim();
        String proof = proofTextArea.getText().trim();
        
        if (userID == null) {
            JOptionPane.showMessageDialog(this, "Please log in before submitting a claim.", "Session Error", JOptionPane.ERROR_MESSAGE);
            Login login = new Login();
            login.setVisible(true);
            this.dispose();
            return;
        }
        
        if (foundItemID.isEmpty() || proof.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Found Item ID and proof cannot be empty.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        ClaimDA claimDA = new ClaimDA();
        if (!claimDA.isClaimableFoundItem(foundItemID)) {
            JOptionPane.showMessageDialog(this, "Found item ID does not exist or is not a found item.", "Claim Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        ClaimRequest claim = new ClaimRequest(userID, foundItemID, null, proof);
        boolean success = claimDA.insertClaim(claim);
        
        if (success) {
            JOptionPane.showMessageDialog(this, "Claim submitted successfully!\nClaim ID: " + claim.getClaimID(), "Success", JOptionPane.INFORMATION_MESSAGE);
            Dashboard dashboard = new Dashboard();
            dashboard.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to submit claim. Please try again.", "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_submitBtnActionPerformed

    private void foundItemsTableMouseClicked(java.awt.event.MouseEvent evt) {
        int selectedRow = foundItemsTable.getSelectedRow();
        if (selectedRow >= 0) {
            Object itemID = foundItemsTable.getValueAt(selectedRow, 0);
            if (itemID != null) {
                foundItemIDTextField.setText(itemID.toString());
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(() -> new SubmitClaim().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton browseBtn;
    private javax.swing.JLabel foundItemIDLabel;
    private javax.swing.JTextField foundItemIDTextField;
    private javax.swing.JLabel foundItemsLabel;
    private javax.swing.JTable foundItemsTable;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JLabel proofLabel;
    private javax.swing.JTextArea proofTextArea;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton submitBtn;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton userserviceBtn;
    // End of variables declaration//GEN-END:variables
}
