/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lostfound.gui;

import lostfound.session.SessionManager;

/**
 *
 * @author danis
 */
public class UserService extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserService.class.getName());

    /**
     * Creates new form UserService
     */
    public UserService() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        homeBtn = new javax.swing.JButton();
        browseBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        userserviceBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        reportlostitemBtn = new javax.swing.JButton();
        submitfounditemBtn = new javax.swing.JButton();
        submitclaimBtn = new javax.swing.JButton();
        editlostreportBtn = new javax.swing.JButton();
        viewclaimsBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(235, 233, 228));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 550));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(244, 85, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 550));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Nirmala Text", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(235, 233, 228));
        jLabel4.setText("Lost&FoundU");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 50, 170, 56);

        homeBtn.setBackground(new java.awt.Color(235, 233, 228));
        homeBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        homeBtn.setText("Home");
        homeBtn.addActionListener(this::homeBtnActionPerformed);
        jPanel2.add(homeBtn);
        homeBtn.setBounds(10, 170, 180, 30);

        browseBtn.setBackground(new java.awt.Color(235, 233, 228));
        browseBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        browseBtn.setText("Browse");
        browseBtn.addActionListener(this::browseBtnActionPerformed);
        jPanel2.add(browseBtn);
        browseBtn.setBounds(10, 220, 180, 30);

        searchBtn.setBackground(new java.awt.Color(235, 233, 228));
        searchBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        searchBtn.setText("Search");
        searchBtn.setToolTipText("");
        searchBtn.addActionListener(this::searchBtnActionPerformed);
        jPanel2.add(searchBtn);
        searchBtn.setBounds(10, 270, 180, 30);

        userserviceBtn.setBackground(new java.awt.Color(235, 233, 228));
        userserviceBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        userserviceBtn.setText("User Service");
        userserviceBtn.setToolTipText("");
        userserviceBtn.addActionListener(this::userserviceBtnActionPerformed);
        jPanel2.add(userserviceBtn);
        userserviceBtn.setBounds(10, 320, 180, 30);

        logoutBtn.setBackground(new java.awt.Color(235, 233, 228));
        logoutBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(this::logoutBtnActionPerformed);
        jPanel2.add(logoutBtn);
        logoutBtn.setBounds(10, 500, 180, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 200, 550);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("User Service");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(230, 50, 120, 22);

        reportlostitemBtn.setBackground(new java.awt.Color(244, 85, 0));
        reportlostitemBtn.setForeground(new java.awt.Color(235, 233, 228));
        reportlostitemBtn.setText("Report Lost Item");
        reportlostitemBtn.addActionListener(this::reportlostitemBtnActionPerformed);
        jPanel1.add(reportlostitemBtn);
        reportlostitemBtn.setBounds(240, 140, 250, 90);

        submitfounditemBtn.setBackground(new java.awt.Color(244, 85, 0));
        submitfounditemBtn.setForeground(new java.awt.Color(235, 233, 228));
        submitfounditemBtn.setText("Submit Found Item");
        submitfounditemBtn.addActionListener(this::submitfounditemBtnActionPerformed);
        jPanel1.add(submitfounditemBtn);
        submitfounditemBtn.setBounds(510, 140, 250, 90);

        submitclaimBtn.setBackground(new java.awt.Color(244, 85, 0));
        submitclaimBtn.setForeground(new java.awt.Color(235, 233, 228));
        submitclaimBtn.setText("Submit Claim");
        submitclaimBtn.addActionListener(this::submitclaimBtnActionPerformed);
        jPanel1.add(submitclaimBtn);
        submitclaimBtn.setBounds(240, 250, 250, 90);

        editlostreportBtn.setBackground(new java.awt.Color(244, 85, 0));
        editlostreportBtn.setForeground(new java.awt.Color(235, 233, 228));
        editlostreportBtn.setText("Manage Report");
        editlostreportBtn.addActionListener(this::editlostreportBtnActionPerformed);
        jPanel1.add(editlostreportBtn);
        editlostreportBtn.setBounds(510, 250, 250, 90);

        viewclaimsBtn.setBackground(new java.awt.Color(244, 85, 0));
        viewclaimsBtn.setForeground(new java.awt.Color(235, 233, 228));
        viewclaimsBtn.setText("View My Claims");
        viewclaimsBtn.addActionListener(this::viewclaimsBtnActionPerformed);
        jPanel1.add(viewclaimsBtn);
        viewclaimsBtn.setBounds(370, 370, 250, 90);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
        Dashboard home = new Dashboard();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void browseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBtnActionPerformed
        // TODO add your handling code here:
        BrowseItems browse = new BrowseItems();
        browse.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_browseBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        SearchItems search = new SearchItems();
        search.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_searchBtnActionPerformed

    private void userserviceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userserviceBtnActionPerformed
        // TODO add your handling code here:
        UserService userService = new UserService();
        userService.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_userserviceBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        SessionManager.getInstance().logout();
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void reportlostitemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportlostitemBtnActionPerformed
        // TODO add your handling code here:
        ReportLostItem lostItem = new ReportLostItem();
        lostItem.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_reportlostitemBtnActionPerformed

    private void submitfounditemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitfounditemBtnActionPerformed
        // TODO add your handling code here:
        ReportFoundItem foundItem = new ReportFoundItem();
        foundItem.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_submitfounditemBtnActionPerformed

    private void submitclaimBtnActionPerformed(java.awt.event.ActionEvent evt) {
        SubmitClaim submitClaim = new SubmitClaim();
        submitClaim.setVisible(true);
        this.dispose();
    }

    private void viewclaimsBtnActionPerformed(java.awt.event.ActionEvent evt) {
        MyClaims myClaims = new MyClaims();
        myClaims.setVisible(true);
        this.dispose();
    }

    private void editlostreportBtnActionPerformed(java.awt.event.ActionEvent evt) {
        ManageReports manageReports = new ManageReports();
        manageReports.setVisible(true);
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserService().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseBtn;
    private javax.swing.JButton editlostreportBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton reportlostitemBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton submitclaimBtn;
    private javax.swing.JButton submitfounditemBtn;
    private javax.swing.JButton userserviceBtn;
    private javax.swing.JButton viewclaimsBtn;
    // End of variables declaration//GEN-END:variables
}
