
package lostfound.gui;

import lostfound.session.SessionManager;


public class UserService extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserService.class.getName());

    /**
     * Creates new form UserService
     */
    public UserService() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        homeBtn1 = new javax.swing.JButton();
        browseBtn1 = new javax.swing.JButton();
        searchBtn1 = new javax.swing.JButton();
        userserviceBtn1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        reportlostitemBtn = new javax.swing.JButton();
        submitfounditemBtn = new javax.swing.JButton();
        submitclaimBtn = new javax.swing.JButton();
        editlostreportBtn = new javax.swing.JButton();
        viewclaimsBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(242, 224, 139));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(null);

        jLabel5.setFont(new java.awt.Font("STHupo", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(231, 85, 49));
        jLabel5.setText("Lost&FoundU");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 100, 190, 56);

        homeBtn1.setBackground(new java.awt.Color(231, 85, 49));
        homeBtn1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        homeBtn1.setForeground(new java.awt.Color(255, 255, 255));
        homeBtn1.setText("HOME");
        homeBtn1.addActionListener(this::homeBtn1ActionPerformed);
        jPanel1.add(homeBtn1);
        homeBtn1.setBounds(30, 170, 180, 30);

        browseBtn1.setBackground(new java.awt.Color(231, 85, 49));
        browseBtn1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        browseBtn1.setForeground(new java.awt.Color(255, 255, 255));
        browseBtn1.setText("BROWSE");
        browseBtn1.addActionListener(this::browseBtn1ActionPerformed);
        jPanel1.add(browseBtn1);
        browseBtn1.setBounds(30, 240, 180, 30);

        searchBtn1.setBackground(new java.awt.Color(231, 85, 49));
        searchBtn1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        searchBtn1.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn1.setText("SEARCH");
        searchBtn1.setToolTipText("");
        searchBtn1.addActionListener(this::searchBtn1ActionPerformed);
        jPanel1.add(searchBtn1);
        searchBtn1.setBounds(30, 310, 180, 30);

        userserviceBtn1.setBackground(new java.awt.Color(231, 85, 49));
        userserviceBtn1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        userserviceBtn1.setForeground(new java.awt.Color(255, 255, 255));
        userserviceBtn1.setText("USER SERVICE");
        userserviceBtn1.setToolTipText("");
        userserviceBtn1.setActionCommand("userService");
        userserviceBtn1.addActionListener(this::userserviceBtn1ActionPerformed);
        jPanel1.add(userserviceBtn1);
        userserviceBtn1.setBounds(30, 380, 180, 30);

        jLabel3.setFont(new java.awt.Font("Bell MT", 1, 48)); // NOI18N
        jLabel3.setText("User Service");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(960, 70, 280, 50);

        reportlostitemBtn.setBackground(new java.awt.Color(231, 85, 49));
        reportlostitemBtn.setFont(new java.awt.Font("STHupo", 0, 24)); // NOI18N
        reportlostitemBtn.setForeground(new java.awt.Color(235, 233, 228));
        reportlostitemBtn.setText("REPORT LOST ITEM");
        reportlostitemBtn.addActionListener(this::reportlostitemBtnActionPerformed);
        jPanel1.add(reportlostitemBtn);
        reportlostitemBtn.setBounds(610, 190, 400, 150);

        submitfounditemBtn.setBackground(new java.awt.Color(231, 85, 49));
        submitfounditemBtn.setFont(new java.awt.Font("STHupo", 0, 24)); // NOI18N
        submitfounditemBtn.setForeground(new java.awt.Color(235, 233, 228));
        submitfounditemBtn.setText("SUBMIT FOUND ITEM");
        submitfounditemBtn.addActionListener(this::submitfounditemBtnActionPerformed);
        jPanel1.add(submitfounditemBtn);
        submitfounditemBtn.setBounds(1180, 190, 400, 150);

        submitclaimBtn.setBackground(new java.awt.Color(231, 85, 49));
        submitclaimBtn.setFont(new java.awt.Font("STHupo", 0, 24)); // NOI18N
        submitclaimBtn.setForeground(new java.awt.Color(235, 233, 228));
        submitclaimBtn.setText("SUBMIT CLAIM");
        submitclaimBtn.addActionListener(this::submitclaimBtnActionPerformed);
        jPanel1.add(submitclaimBtn);
        submitclaimBtn.setBounds(620, 380, 400, 150);

        editlostreportBtn.setBackground(new java.awt.Color(231, 85, 49));
        editlostreportBtn.setFont(new java.awt.Font("STHupo", 0, 24)); // NOI18N
        editlostreportBtn.setForeground(new java.awt.Color(235, 233, 228));
        editlostreportBtn.setText("MANAGE REPORT");
        editlostreportBtn.addActionListener(this::editlostreportBtnActionPerformed);
        jPanel1.add(editlostreportBtn);
        editlostreportBtn.setBounds(1180, 380, 400, 150);

        viewclaimsBtn.setBackground(new java.awt.Color(231, 85, 49));
        viewclaimsBtn.setFont(new java.awt.Font("STHupo", 0, 24)); // NOI18N
        viewclaimsBtn.setForeground(new java.awt.Color(235, 233, 228));
        viewclaimsBtn.setText("VIEW MY CLAIMS");
        viewclaimsBtn.addActionListener(this::viewclaimsBtnActionPerformed);
        jPanel1.add(viewclaimsBtn);
        viewclaimsBtn.setBounds(900, 580, 400, 150);

        logoutBtn.setBackground(new java.awt.Color(235, 233, 228));
        logoutBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        logoutBtn.setText("LOGOUT");
        logoutBtn.addActionListener(this::logoutBtnActionPerformed);
        jPanel1.add(logoutBtn);
        logoutBtn.setBounds(30, 950, 180, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lostfound/gambar/bluewhitebg.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 240, 1080);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reportlostitemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportlostitemBtnActionPerformed
        // TODO add your handling code here:
        ReportLostItem lostItem = new ReportLostItem();
        lostItem.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_reportlostitemBtnActionPerformed

    private void submitfounditemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitfounditemBtnActionPerformed
        // TODO add your handling code here:
        ReportFoundItem foundItem = new ReportFoundItem();
        foundItem.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_submitfounditemBtnActionPerformed

    private void homeBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtn1ActionPerformed
        // TODO add your handling code here:
        Dashboard home = new Dashboard();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeBtn1ActionPerformed

    private void browseBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBtn1ActionPerformed
        // TODO add your handling code here:
        BrowseItems browse = new BrowseItems();
        browse.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_browseBtn1ActionPerformed

    private void searchBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtn1ActionPerformed
        // TODO add your handling code here:
        SearchItems search = new SearchItems();
        search.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_searchBtn1ActionPerformed

    private void userserviceBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userserviceBtn1ActionPerformed
        // TODO add your handling code here:
        UserService userService = new UserService();
        userService.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_userserviceBtn1ActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        SessionManager.getInstance().logout();
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void submitclaimBtnActionPerformed(java.awt.event.ActionEvent evt) {
        SubmitClaim submitClaim = new SubmitClaim();
        submitClaim.setVisible(true);
        this.dispose();
    }

    private void viewclaimsBtnActionPerformed(java.awt.event.ActionEvent evt) {
        MyClaims myClaims = new MyClaims();
        myClaims.setVisible(true);
        this.dispose();
    }

    private void editlostreportBtnActionPerformed(java.awt.event.ActionEvent evt) {
        ManageReports manageReports = new ManageReports();
        manageReports.setVisible(true);
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserService().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseBtn1;
    private javax.swing.JButton editlostreportBtn;
    private javax.swing.JButton homeBtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton reportlostitemBtn;
    private javax.swing.JButton searchBtn1;
    private javax.swing.JButton submitclaimBtn;
    private javax.swing.JButton submitfounditemBtn;
    private javax.swing.JButton userserviceBtn1;
    private javax.swing.JButton viewclaimsBtn;
    // End of variables declaration//GEN-END:variables
}
